### ISSUE TITLE
Refactor `Bertscore` tests

### ISSUE THREAD

**Issue by stancld** [Lightning-AI/torchmetrics#1110]
Bertscore test design is currently a bit odd considering the level of unification of the whole package => Refactor `Bertscore` tests to use a standard test suite.

**Comment by Borda** [comment]
@stancld, how is it going here? :)

**Comment by stancld** [comment]
@Borda Just wrote down to my TODO list for tomorrow a few minutes ago. I guess I'll send a PR tomorrow then, shouldn't be anything complicated.
