### ISSUE TITLE
`MeanAveragePrecision` (map) returns -1.0 if `max_detection_thresholds` is changed

### ISSUE THREAD

**Issue by marckatzenmaier** [Lightning-AI/torchmetrics#1153]
## 🐛 Bug
I found a bug when changing the max_detection_thresholds of MeanAveragePrecision to a large number e.g. [1, 10, 1000] the result of the map calculation becomes -1.0
I wanted to increase the number of detections per image since my data has up to several thousand instances per image. I detected that the same problem occurs with the example given in the class definition.

### To Reproduce
Run the example from the function definition with max_detection_thresholds=[1, 10, 1000] instead of the default [1, 10, 100].

#### Code sample
```py
import torch
from torchmetrics.detection.mean_ap import MeanAveragePrecision
preds = [dict(
              boxes = torch.tensor([[258.0, 41.0, 606.0, 285.0]]),
              scores = torch.tensor([0.536]),
              labels = torch.tensor([0]),
             )]
target = [dict(
               boxes = torch.tensor([[214.0, 41.0, 562.0, 285.0]]),
               labels = torch.tensor([0]),
             )]
metric = MeanAveragePrecision(max_detection_thresholds=[1, 10, 1000])
metric.update(preds, target)
from pprint import pprint
pprint(metric.compute())
```
Output:
```
{'map': tensor(-1.),
 'map_50': tensor(1.),
 'map_75': tensor(1.),
 'map_large': tensor(0.6000),
 'map_medium': tensor(-1.),
 'map_per_class': tensor(-1.),
 'map_small': tensor(-1.),
 'mar_1': tensor(0.6000),
 'mar_10': tensor(0.6000),
 'mar_1000': tensor(0.6000),
 'mar_1000_per_class': tensor(-1.),
 'mar_large': tensor(0.6000),
 'mar_medium': tensor(-1.),
 'mar_small': tensor(-1.)}
```
### Expected behavior

Get the same output as with [1, 10, 100]:
```
{'map': tensor(0.6000),
 'map_50': tensor(1.),
 'map_75': tensor(1.),
 'map_large': tensor(0.6000),
 'map_medium': tensor(-1.),
 'map_per_class': tensor(-1.),
 'map_small': tensor(-1.),
 'mar_1': tensor(0.6000),
 'mar_10': tensor(0.6000),
 'mar_100': tensor(0.6000),
 'mar_100_per_class': tensor(-1.),
 'mar_large': tensor(0.6000),
 'mar_medium': tensor(-1.),
 'mar_small': tensor(-1.)}
```

### Environment
- python 3.9
- pytorch: 1.10
- TorchMetrics: 0.9.0

Thanks for your help.

**Comment by SkafteNicki** [comment]
Closed by #1712 .

**Comment by RocketFlash** [comment]
Same issue using last library version

**Comment by RocketFlash** [comment]
@SkafteNicki could you recommend what to do ?

**Comment by RocketFlash** [comment]
@SkafteNicki it seems something wrong with pycocotools, I've tried faster version of COCOEval (https://github.com/MiXaiLL76/faster_coco_eval) and it calculates mAP correctly (not -1)

**Comment by Borda** [comment]
> it seems something wrong with pycocotools

What version are using as the original repo was forked and some OSS development continued
