### ISSUE TITLE
Docs: pages don't show in search results

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/torchmetrics#1340]
This is not an issue with the package exactly, but I think something is wrong with your Google setup for search indexing.

E.g. this Google search returns no results:
https://www.google.com/search?q=torchmetrics+%22Perplexity+measures+how+well+a+language%22

Even though that text is copy pasted from the Perplexity page here: https://torchmetrics.readthedocs.io/en/stable/text/perplexity.html

BTW I noticed the issue since a Google search for "torchmetrics perplexity" returns nothing useful, but I eventually found that such a page does exist. A bing search returns the correct page as the first result.

**Comment by Borda** [comment]
@yurijmikhalevich could we also fix it on the public template? :)

**Comment by yurijmikhalevich** [comment]
@Borda, this is a different issue. Our website and docs can use a proper sitemap to help Google with indexing.

**Comment by davidgilbertson** [comment]
You don't need a sitemap for Google to index the site correctly (since your site is relatively small/static and the links to pages are plain hyperlinks). You definitely don't need to list every page ([source](https://youtu.be/JlamLfyFjTA?t=140)). Google will follow links from the entry points you provide, either in the Search Console, or those high-level pages in the sitemap.

The cause of the problem may be reported in your "[Page indexing report](https://support.google.com/webmasters/answer/7440203?hl=en)" on the Google Search Console.

**Comment by SkafteNicki** [comment]
For now lets consider the problem to be solved as the particular search now shows up correctly:
![image](https://user-images.githubusercontent.com/24896311/229505125-28376d50-dc4f-47c4-8986-da30919c4589.png)
Closing issue.
