### ISSUE TITLE
Add Critical Success Index to Torchmetrics

### ISSUE THREAD

**Issue by sortland33** [Lightning-AI/torchmetrics#1509]
## 🚀 Feature

In weather forecasting, critical success index (CSI) is widely used to evaluate model skill. However, Torchmetrics does not have this metric. Instead, one must determine the true positives, etc. and calculate it locally which can get a bit clunky. I think it would be good for weather applications of artificial intelligence to be able to call this metric directly from torchmetrics.

### Motivation

I find myself bogged down with trying to figure out CSI for a paper I am writing to present a model to the forecasting community. Since they use this metric frequently, if I don't have this metric my model may not be taken seriously. So, it would be nice to have a function to do this. 

### Pitch

Create a Torchmetrics metric for Critical Success Index. 

### Alternatives

An alternative would be to have documentation for how to calculate this metric from existing metrics. 

### Additional context

Definition of critical success index from a brief google search and from NOAA: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/125407478/218861518-6051503f-1a74-4e9a-b6ee-6d30db969bf0.png">

The critical success index is usually calculated at many thresholds (i.e. .1, .2, .4) and used to determine which threshold the model performs best at.

**Comment by justusschock** [comment]
Hi @sortland33 ,

We would definitely welcome such an addition. Once you figured it out, would you submit a PR to add it here for future use both by yourself and others?

**Comment by sortland33** [comment]
Hi @justusschock (and @SkafteNicki ?), 

I wrote some code for this new metric, but it is specific to a 2 class case. This is my first time ever submitting a PR- do I need to try to generalize it to multilabel and more than 2 classes before I submit a PR?

**Comment by SkafteNicki** [comment]
Hi @sortland33,
You can send a PR with what you have, then it will be easier to identify what to do next :)

**Comment by miskfi** [comment]
Hello, I stumbled across this issue. I implemented CSI for my own project, so I thought I might polish up and contribute what I have. I don't have any unit tests yet, as I didn't know what implementation could be used as a reference (torchmetrics and scikit-learn have Jaccard index but that requires different inputs than CSI)
