### ISSUE TITLE
LPIPS generates warning.

### ISSUE THREAD

**Issue by zhou13** [Lightning-AI/torchmetrics#1546]
### To Reproduce

Steps to reproduce the behavior...

```
>>> from torchmetrics.image.lpip import LearnedPerceptualImagePatchSimilarity
>>> lpips = LearnedPerceptualImagePatchSimilarity()
/miniconda/envs/iris/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/miniconda/envs/iris/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
```

### Expected behavior

No Warning is generated.

### Environment

```
>>> torchvision.__version__
'0.14.1+cu116'
>>> torchmetrics.__version__
'0.11.1'
```

**Comment by SkafteNicki** [comment]
@Borda what should we do here?
The warning is raised by a third-party dependency for this specific metric that have not been updated in 2 years, so unlikely that it will be update to support newer versions of torchvision.
Should we copy in the relevant code with changes (around 400 LOC) or what to do?

**Comment by Borda** [comment]
We can try to wrap thecall and suppress a specific varning... for example: https://gist.github.com/hexsprite/06d5c5cd13cbcae4ba24

> Should we copy in the relevant code with changes (around 400 LOC) or what to do?

If you think we have some distingushibale changes and being pure copy-paste... also depends on license conditions

**Comment by SkafteNicki** [comment]
> We can try to wrap thecall and suppress a specific varning... for example: https://gist.github.com/hexsprite/06d5c5cd13cbcae4ba24
> 
> > Should we copy in the relevant code with changes (around 400 LOC) or what to do?
> 
> If you think we have some distingushibale changes and being pure copy-paste... also depends on license conditions

But we should not suppress it, because it's an compatibility warning from torchvision about future versions. So that metric will break in the future.

I think the solution will be copy over what we need to have the metric also working in the future.
