### ISSUE TITLE
Naming of pairwise_cosine_similarity isn't accurate in all cases

### ISSUE THREAD

**Issue by wderekjones** [Lightning-AI/torchmetrics#1645]
I was working on a project which depended heavily on the semantics of this function returning cosine similarity. In a somewhat tired state, I misread the documentation and believed that the function was returning distances instead. It took a few hours for me to realize that this function actually does two things depending on the number of arguments after I had spent some time re-generating some of my results. 

I am requesting that this not be the case and that a separate function for cosine distance just be implemented, which should be fairly straightforward. I understand the convenience element here of one function handling two different cases of a single tensor and pair of tensors however as it is already so easy to conflate cosine distance versus similarity, I think it should just do one thing rather than anticipate what to do in the case it only receives one array as an argument. I just found it unintuitive given the name of the function is `pairwise_cosine_similarity` and confusing and I likely wont be the last person to be confused the documentation/semantics of this function. 

Thank you!

**Comment by SkafteNicki** [comment]
Hi @wderekjones, thanks for raising this issue.
We modelled our pairwise interface to be identical to scikit-learns: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html, to make sure that users that are coming from numpy/sklearn expects the same format.
I would really like to keep this as one function, but I kind of get the problem you are hinting at. Do you have recommendations for improving the documentation https://torchmetrics.readthedocs.io/en/stable/pairwise/cosine_similarity.html? As far as I can see, we try to make the aware that the function has two "modes" in:
* The docstring just below the formula
* In the returns section (this could probably be improved)
* By having two examples showcasing both modes
