### ISSUE TITLE
Inconsistent imports for BLEUScore and ROUGEScore

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/torchmetrics#1654]
It appears that the imports for BLEUScore and ROUGEScore are inconsistent, which can be confusing for users.

I would recommend either changing both to 

```python
from torchmetrics.text import BLEUScore, ROUGEScore
```

or 

```python
from torchmetrics import BLEUScore, ROUGEScore
```

![screenshot_2023-03-25_at_8 00 11_am_480](https://user-images.githubusercontent.com/5618407/227720663-ebc62abc-817a-4d69-84a6-af2865c3a928.png)
![screenshot_2023-03-25_at_8 01 51_am_720](https://user-images.githubusercontent.com/5618407/227720667-ebdde541-4960-4f2c-960a-111d9fa3033b.png)

**Comment by SkafteNicki** [comment]
The arguments were laid out on slack but just for reference we introduced this pattern where metrics that have a third party package dependency needed to be imported for sub package back in v0.7, described in this blogpost:
https://devblog.pytorchlightning.ai/torchmetrics-v0-7-more-metrics-and-improved-api-a02de396c044

@Borda, @justusschock lets take a discussion here: I see two ways of standardizing this:
1. Either every metric is available from root, but metrics with third-party packages will fail on initialization. Plus side is that this is backward compatible, bad is that it will fill up root namespace even more.
2. Every metric needs to be imported from their sub package. Not backward compatible but maybe that is not a problem if the next release will be v1.0 so we can break things.

**Comment by rasbt** [comment]
@SkafteNicki thanks for explaining, the rationale makes sense regarding 3rd party packages.

Still, this is a bit unintuitive for a user. E.g., a user might not care about implementation details (whether something under the hood is based on a third-party or not; also the implementation under the hood may change in the future, which should not affect the UI.

So, I would definitely suggest going with your proposed solution 1 or 2. That might need further discussion though, but I think the UI should definitely be decoupled from implementation details.

**Comment by justusschock** [comment]
Personally, I am for version 2. Otherwise dependency handling would either be more complicated or the package could effectively only be used if users have all packages imported. IMO there shouldn't be an exception then (not even for accuracy etc). @SkafteNicki @Borda opinions?

**Comment by SkafteNicki** [comment]
I am not sure what the best option here is, but we already determined to put only put `Accuracy` in root and the specialized versions `BinaryAccuracy`, `MulticlassAccuracy`, `MultilabelAccuracy` in subdomain due to cluttering in the root namespace, so that would automatically make option 1 a bad solution.

@rasbt do you have any opinion from a user standpoint what you would like?

**Comment by rasbt** [comment]
@SkafteNicki I think that option 2 is quite intuitive from a UI perspective. No one would mind to import text-specific metrics from a `torchmetric.text` submodule. I guess it gets more tricky when we have metrics that are used across different fields. Those should probably be in the main namespace then (like accuracy, MAE, ROC AUC, etc.)

**Comment by stancld** [comment]
@Borda Sounds reasonable. Should we go with a deprecated warning here for one minor release?

**Comment by Borda** [comment]
> Should we go with a deprecated warning here for one minor release?

as next will be 1.0 we do not ned any deprecation

**Comment by rasbt** [comment]
> as next will be 1.0 we do not ned any deprecation

I would say it would be a nice thing to do though.

**Comment by Borda** [comment]
> I would say it would be a nice thing to do, though.

well and how long would you expect to keep it, til 2.0?
Maror release is expected to change some API, as for example `pandas`

**Comment by rasbt** [comment]
> well and how long would you expect to keep it, til 2.0?

1.1 or 1.2.

> Maror release is expected to change some API, as for example pandas

That's fair, but at the same time, users constantly complain about that, so a bit of a meeting in the middle would be a nice gesture. If a deprecation is too complicated because of the submodule reorg, maybe don't worry about it. But I am just saying that users really don't like major API changes. So even if it is a 1.0, a slight deprecation warning for 1.1 or so would be slightly nicer.

**Comment by Borda** [comment]
> > well and how long would you expect to keep it, til 2.0?
> 
> 1.1 or 1.2.

Then we will be doing fuzzy semantic version and we shall not talk about 1.0 as we just bump version...

> > Maror release is expected to change some API, as for example pandas
> 
> That's fair, but at the same time, users constantly complain about that, so a bit of a meeting in the middle would be a nice gesture. If a deprecation is too complicated because of the submodule reorg, maybe don't worry about it. But I am just saying that users really don't like major API changes. So even if it is a 1.0, a slight deprecation warning for 1.1 or so would be slightly nicer.

True, but we have not made any major yet so users shall kniw that API can change any time so having at least one major shall be something they want so the API become stable

Users can also stay with their version noone pushing them to upgrade =)

**Comment by Borda** [comment]
@rasbt we can also reconsider breaking chnage with required `task=...` and hold it for 1.0, see #1670

**Comment by Kh4L** [comment]
Bumped into this issue wtih 1.3.2 (latest): 
```
root@mysystem:/workspace/MMGL# pip show torchmetrics
Name: torchmetrics
Version: 1.3.2
Summary: PyTorch native Metrics
Home-page: https://github.com/Lightning-AI/torchmetrics
Author: Lightning-AI et al.
Author-email: name@pytorchlightning.ai
License: Apache-2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: lightning-utilities, numpy, packaging, torch
Required-by: gp
root@mysystem:/workspace/MMGL# python -c "from torchmetrics import ROUGEScore"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'ROUGEScore' from 'torchmetrics' (/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py)
root@mysystem:/workspace/MMGL# python -c "from torchmetrics.text import ROUGEScore"
root@mysystem:/workspace/MMGL# echo $?
0
```
@Borda @SkafteNicki

**Comment by Borda** [comment]
that is correct; we moved all metrics which need an addition dependency to the second level
