### ISSUE TITLE
MS-SSIM for 3D input

### ISSUE THREAD

**Issue by Warvito** [Lightning-AI/torchmetrics#1656]
Similar to the ssim index in 

https://github.com/Lightning-AI/metrics/blob/a6320cfae434b96d41fdf94d6387f4aed02b9062/src/torchmetrics/functional/image/ssim.py#L161

the contrast_sensitivity should remove the pad_d in the 3D case in  

https://github.com/Lightning-AI/metrics/blob/a6320cfae434b96d41fdf94d6387f4aed02b9062/src/torchmetrics/functional/image/ssim.py#L167

**Comment by justusschock** [comment]
Hey @Warvito , would you be interested in contributing a 3D port?
