### ISSUE TITLE
`MultioutputWrapper` does not squeeze `kwargs`

### ISSUE THREAD

**Issue by apointa** [Lightning-AI/torchmetrics#1672]
Hi there,

`MultioutputWrapper` class provides the option `squeeze_outputs`. If this is set the output should be squeezed on the index select dimension.
Altough this happens for the `args` it does not happen for `kwargs`

Here is are the where it happens, but it is only done for the `args` not for the `kwargs`.
https://github.com/Lightning-AI/torchmetrics/blob/af52ba6a422e9f8c99853396d78882015a3c6fe3/src/torchmetrics/wrappers/multioutput.py#L105-L108

Should be a one-line change. if needed i can provide an PR

Greetings Andi

**Comment by SkafteNicki** [comment]
Hi @apointa, feel free to send a PR with the change :)

**Comment by SkafteNicki** [comment]
Hi again @apointa, since the fix was so simple I have just done it already in PR #1675
