### ISSUE TITLE
add Precision At Fixed Recall

### ISSUE THREAD

**Issue by fcakyon** [Lightning-AI/torchmetrics#1678]
## 🚀 Feature

Calculate the highest possible precision value given the minimum recall thresholds provided. This could be done by first calculating the precision-recall curve for different thresholds and then finding the precision for a given recall level.

### Motivation

PrecisionAtFixedRecall is the most used metric for real-world classification systems. Check Twitter NSFW detector source code: https://github.com/twitter/the-algorithm/blob/ec83d01dcaebf369444d75ed04b3625a0a645eb9/trust_and_safety_models/nsfw/nsfw_media.py#L143

It would be very useful to have it included in the torchmetrics library.

### Pitch

Calculate the highest possible precision value given the minimum recall thresholds provided. This could be done by first calculating the precision-recall curve for different thresholds and then finding the precision for a given recall level.

### Additional context

Similar to [recall_at_fixed_precision](https://torchmetrics.readthedocs.io/en/stable/classification/recall_at_fixed_precision.html).

**Comment by williamFalcon** [comment]
@fcakyon yes, let's add it! want to submit the PR? we can help you land it.
