### ISSUE TITLE
ModuleNotFoundError: No module named 'torchmetrics.functional.multimodal'

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [Lightning-AI/torchmetrics#1739]
## 🐛 Bug

Hi, I have met a problem when running torchmetric by importing clip_score, the error is as following. Does anybody have met this and how to solve?

> ModuleNotFoundError: No module named 'torchmetrics.functional.multimodal'

### To Reproduce

Here is the code to reproduce:

<details>
  <summary>Code sample</summary>

> tensor(24.4255)

### Environment

- TorchMetrics version :  '0.6.0' (pip install)
- PyTorch :                      2.0.0
-  OS (e.g., Linux):          Ubuntu20.0

**Comment by stancld** [comment]
Hi @JiaojiaoYe1994, `CLIPScore` has been added since release `0.11.0`. You would need then to upgrade `torchmetrics` accordingly to be able to use the metric.

**Comment by SkafteNicki** [comment]
Yes, as @stancld we added clip score in this PR https://github.com/Lightning-AI/torchmetrics/pull/1314 which became part of v0.11.0 of torchmetrics. Please upgrade your package:
```
pip install -U torchmetrics
```
to get the metric.
Closing issue.
