### ISSUE TITLE
Add a `PlottableMetric` class

### ISSUE THREAD

**Issue by ValerianRey** [Lightning-AI/torchmetrics#1740]
## 🚀 Feature

Add a `PlottableMetric` class, that will contain all the code related to metric plotting.

### Motivation

Currently, `plot` is an "abstract" method defined in `Metric`. To fully respect [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), all `Metric` subclasses should give an implementation to `plot`. 

Most user-defined `Metric` sub-classes do not override `plot` (because they were coded prior to the `plot` feature). Also, some built-in `Metric` sub-classes, such as `BinaryGroupStatRates` , `MultilabelStatScores`, `CompositionalMetric`, `CatMetric`, etc., do not override `plot`.

### Pitch

A solution would be to remove the `plot` method (and related attributes) from `Metric`, and put them in a `PlottableMetric` class. Metrics that are plottable will simply extend both `Metric` and `PlottableMetric`. Metrics that should not be plottable will not extend `PlottableMetric`.

### Additional Context

I have not used the `plot` functionality yet, and I didn't work on it at all, so I'd be happy to learn more about the long-term goals for this `plot` feature (do you maybe plan to make all `Metric` sub-classes override it?)

**Comment by SkafteNicki** [comment]
@Borda @justusschock opinions on this?

**Comment by Borda** [comment]
As we do not subclass Classification, Regression I am not sure what we would gain from this abstraction; we can get the same by adding an attribute or, in its parent class, set the `plot` as an ellipsis so we can check that this method is not implemented?
