### ISSUE TITLE
Add a wrapper adapted to multi-task learning

### ISSUE THREAD

**Issue by ValerianRey** [Lightning-AI/torchmetrics#1741]
## 🚀 Feature

Add a wrapper adapted to multi-task learning. Given a list of model outputs and a list of labels, it should be able to compute a different metric (or several different metrics) on each output.

### Motivation

When doing multi-task learning, we have several outputs, and the metric that we want to compute on each output is generally different. 

For instance, in image detection with K classes, the output could consist of 4 neurons for bounding box location (pos_x, pos_y, height, width), and K neurons for the class of the detected object. We would like to have a way to compute some regression metrics (like MSE, MAE, etc...) on the outputs corresponding to the bounding box locations, and to compute some classification metrics (like Accuracy) on the outputs corresponding to the class. 

An idea could be to simply generalize `MultioutputWrapper` to use a list of `base_metric` rather than a single, duplicated, `base_metric`. But in the previous example, the output and the label are `tuple[Tensor, Tensor]` (the first element is a `Tensor` of shape [4], the second element is a `Tensor` of shape [K]), and `MultioutputWrapper` works with `Tensor` only.

### Pitch

Add a `MultitaskWrapper` class that would take a list of `Metric`s at initialization (or maybe a `MetricCollection`, or an `Iterable[Metric]`), and whose `update` signature would look like:
```python
def update(self, preds: Iterable[Tensor], targets: Iterable[Tensor]) -> None:
```

**Comment by SkafteNicki** [comment]
Hi @ValerianRey, that sounds like an excellent addition to torchmetrics.
However, I am still a bit in doubt what it should look like. Maybe you could give a concreate coding example how you would like the metric to work?

What I understand you are looking for is something like this?
```python
from torchmetrics import Accuracy, MeanSquaredError, MultitaskWrapper
metrics = MultiTaskWrapper(
   Accuracy(), MeanSquaredError()
)

class_probs, bounding_box_pred = model(some_input)
metrics.update([class_probs, bounding_box_pred], [class_targets, bounding_box_target])
val = metrics.compute()  # return dict with both accuracy + mse
```

**Comment by ValerianRey** [comment]
I'll work on a draft implementation later this week!

**Comment by SkafteNicki** [comment]
> I'll work on a draft implementation later this week!

Alright, I assign the issue to you and look forward to your draft :]
