### ISSUE TITLE
Problems with "BinaryCalibrationError" when perfectly calibrated

### ISSUE THREAD

**Issue by wkml** [Lightning-AI/torchmetrics#1744]
### To Reproduce

If my data is:

```python
import torch
logits = torch.tensor([0,1,0,1]).float()
labels = torch.tensor([0,1,0,1])
```

Then I calibrate using BinaryCalibrationError:
```python
from torchmetrics.classification import BinaryCalibrationError
ECE_metric = BinaryCalibrationError(n_bins=15, norm='l1')
ece = ECE_metric(logits, labels)
```
This causes an error:
[/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/classification/calibration_error.py](https://localhost:8080/#) in _binning_bucketize(confidences, accuracies, bin_boundaries)
     46     indices = torch.bucketize(confidences, bin_boundaries) - 1
     47 
---> 48     count_bin.scatter_add_(dim=0, index=indices, src=torch.ones_like(confidences))
     49 
     50     conf_bin.scatter_add_(dim=0, index=indices, src=confidences)

RuntimeError: index -1 is out of bounds for dimension 0 with size 15

**Comment by wkml** [comment]
Hello, I have received your email.

**Comment by SkafteNicki** [comment]
Hi @wkml, thanks for reporting this issue.
Happy to report that it is already solved on master (this PR to be specific: https://github.com/Lightning-AI/torchmetrics/pull/1648). Either update to master now
``` 
pip install https://github.com/Lightning-AI/torchmetrics/archive/master.zip
```
or wait for the next release.
