### ISSUE TITLE
NLTK punkt bug

### ISSUE THREAD

**Issue by ShaojieJiang** [Lightning-AI/torchmetrics#1779]
## 🐛 Bug

[This line](https://github.com/Lightning-AI/torchmetrics/blob/17c0e9fdf636cff7299fc3d86fa5e3709b603737/src/torchmetrics/functional/text/rouge.py#L52) `nltk.data.find("tokenizers/punkt.zip")` always raises LookupError:
```
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt.zip

  Searched in:
    - '/home/**/nltk_data'
    - '/data/**/anaconda3/nltk_data'
    - '/data/**/anaconda3/share/nltk_data'
    - '/data/**/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

Maybe it should be `nltk.data.find("tokenizers/punkt")`?
After the downloading that follows, this calling to `find` without .zip extension works successfully.

### To Reproduce

```
import nltk

try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    try:
        nltk.download("punkt", quiet=True, force=False, halt_on_error=False, raise_on_error=True)
    except ValueError:
        raise OSError(
            "`nltk` resource `punkt` is not available on a disk and cannot be downloaded as a machine is not "
            "connected to the internet."
        )

nltk.data.find("tokenizers/punkt.zip")
```

### Expected behavior

No error raised.

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.11.4, pip installed
- Python & PyTorch Version (e.g., 1.0): Python 3.7.10, PyTorch 1.13.0
- Any other relevant information such as OS (e.g., Linux): Ubuntu 18.04, nltk 3.8.1

### Additional context

The above information should be enough.

**Comment by Trace2333** [comment]
Same problem. And the function always raises the error in epoch 2 or later, it has terminated my training serval times......
