### ISSUE TITLE
Passing `max_detection_thresholds` to `MeanAveragePrecision` breaks the calculation

### ISSUE THREAD

**Issue by aamster** [Lightning-AI/torchmetrics#1795]
## 🐛 Bug

Passing `max_detection_thresholds` other than 100 to `MeanAveragePrecision` causes `.compute` to return -1 for map

### To Reproduce

Take the example at https://github.com/Lightning-AI/torchmetrics/blob/master/examples/detection_map.py but pass `max_detection_thresholds=[50]` to `MeanAveragePrecision`

### Expected behavior

it should not return -1

**Comment by SkafteNicki** [comment]
Hi @aamster,
Could you try running from master?
```python
pip install https://github.com/Lightning-AI/torchmetrics/archive/master.zip
```
To me it seems the issue was fixed by this PR: https://github.com/Lightning-AI/torchmetrics/pull/1712, because running the example as you are proposing seems to be producing the right answer.

**Comment by aamster** [comment]
@SkafteNicki it is fixed on master. I will close this issue then
