### ISSUE TITLE
PCC gives error with AMP

### ISSUE THREAD

**Issue by shenoynikhil** [Lightning-AI/torchmetrics#1813]
## 🐛 Bug

On turning on Automatic Mixed Precision, there is an error in Pearson Correlation Coefficient computation at this [line](https://github.com/Lightning-AI/torchmetrics/blob/962f82db7b0ab7ca32fe050aba45f1d3f9fe64c9/src/torchmetrics/functional/regression/pearson.py#L95). The trace is as follows,
```
  File "/home/nikhil/miniconda3/envs/mrl/lib/python3.8/site-packages/torchmetrics/functional/regression/pearson.py", line 80, in _pearson_corrcoef_compute                                              
    corrcoef = (corr_xy / (var_x * var_y).sqrt()).squeeze()                                                                                                                                             
RuntimeError: "sqrt_vml_cpu" not implemented for 'Half'
```

Turning AMP off, it fixes it. 

### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary>Code sample</summary>

</details>

### Environment

- TorchMetrics version : `0.11.4` installed via `pip`
- Python & PyTorch Version (e.g., 1.0): `Python 3.8`, `Torch 2.0.1+cu118`
- Any other relevant information such as OS (e.g., Linux): `Linux`

**Comment by stancld** [comment]
Hi, I think we can replace `x.sqrt()` call with `x ** 0.5`, which can be also computed when passing `16bit` float tensor.

**Comment by SkafteNicki** [comment]
@shenoynikhil feel free to send a PR with the change proposed by @stancld :]

**Comment by shenoynikhil** [comment]
The fix gives this error,
`RuntimeError: "pow" not implemented for 'Half'`
It does not have a problem with `bfloat16` but has a problem with `float16`.
