### ISSUE TITLE
Different SSIM results on cpu device and gpu device.

### ISSUE THREAD

**Issue by h2hermit** [Lightning-AI/torchmetrics#1864]
Run the following codes.
```python
from torchmetrics import StructuralSimilarityIndexMeasure
import torch
preds = torch.rand([16, 3, 256, 256], generator=torch.manual_seed(42)).to('cpu')
target = torch.rand([16, 3, 256, 256], generator=torch.manual_seed(123)).to('cpu')
ssim_cpu = StructuralSimilarityIndexMeasure(data_range=1.0)

ssim_cuda = StructuralSimilarityIndexMeasure(data_range=1.0).to('cuda')
preds_cuda = preds.clone().cuda()
target_cuda = target.clone().cuda()

print('ssim_cpu:',ssim_cpu(target,preds))
print('ssim_cuda:', ssim_cuda(preds_cuda, target_cuda))
```
The output is
```python
ssim_cpu: tensor(0.0064)
ssim_cuda: tensor(0.0053, device='cuda:0')
```

**Comment by SkafteNicki** [comment]
Hi @h2hermit, thanks for reporting this issue.
I cannot reproduce this. When running the provided code locally (window machine, Intel cpu, 1060 Nvidia GPU) I get `tensor(0.0064)` for both the CPU and GPU computation. I then tried out in colab:
https://colab.research.google.com/drive/1hvpbe0cGl6lx6FsTVzz1nIinbFdY16Nt?usp=sharing
which again give `tensor(0.0064)` for both the CPU and GPU computation.

Thus, it seems to be something with your GPU + torchmetrics that is the problem. Could you inform what hardware you are running on? Also just to be sure which version of torch + torchmetrics you are using?

**Comment by h2hermit** [comment]
> Hi @h2hermit, thanks for reporting this issue. I cannot reproduce this. When running the provided code locally (window machine, Intel cpu, 1060 Nvidia GPU) I get `tensor(0.0064)` for both the CPU and GPU computation. I then tried out in colab: https://colab.research.google.com/drive/1hvpbe0cGl6lx6FsTVzz1nIinbFdY16Nt?usp=sharing which again give `tensor(0.0064)` for both the CPU and GPU computation.
> 
> Thus, it seems to be something with your GPU + torchmetrics that is the problem. Could you inform what hardware you are running on? Also just to be sure which version of torch + torchmetrics you are using?

Thanks for responce. My gpu device is NVIDIA GeForce RTX 3090 and the version of torchmetrics is 0.11.4.  The codes and results are following.
```python
from torchmetrics import StructuralSimilarityIndexMeasure
import torch
import torchmetrics
import os 
os.environ['CUDA_VISIBLE_DEVICES'] = '2'
preds = torch.rand([16, 3, 256, 256], generator=torch.manual_seed(42)).to('cpu')
target = torch.rand([16, 3, 256, 256], generator=torch.manual_seed(123)).to('cpu')
ssim_cpu = StructuralSimilarityIndexMeasure(data_range=1.0)

ssim_cuda = StructuralSimilarityIndexMeasure(data_range=1.0).to('cuda')
preds_cuda = preds.clone().cuda()
target_cuda = target.clone().cuda()

print('ssim_cpu:',ssim_cpu(preds,target))
print('ssim_cuda:', ssim_cuda(preds_cuda, target_cuda))
print('torchmetrics.__version__:', torchmetrics.__version__)
print('torch.__version__:', torch.__version__)
print('torch.cuda.get_device_name(0):', torch.cuda.get_device_name(0))
```

```python
ssim_cpu: tensor(0.0064)
ssim_cuda: tensor(0.0053, device='cuda:0')
torchmetrics.__version__: 0.11.4
torch.__version__: 1.10.0
torch.cuda.get_device_name(0): NVIDIA GeForce RTX 3090
```
But when I changed the gpu device from NVIDIA GeForce RTX 3090 to Tesla V100-PCIE-32GB, I got the correct results.
```python
ssim_cpu: tensor(0.0064)
ssim_cuda: tensor(0.0064, device='cuda:0')
torchmetrics.__version__: 0.11.4
torch.__version__: 1.10.0
torch.cuda.get_device_name(0): Tesla V100-PCIE-32GB
```

**Comment by SkafteNicki** [comment]
@h2hermit I know that the NVIDIA GeForce RTX 3090 have previous given us some trouble by given a different result than other hardware, but we never been able to narrow down what the real issue is. I know if you just google "pytorch 3090" you will see lengthy discussions about the compatibility of that card with pytorch.

For now could you also provide the output of:
```nvcc --version```

to check what version of cuda you are running?
Of cause it is going to be hard for me to help with debugging, since I do not have access to 3090 card.

**Comment by h2hermit** [comment]
> @h2hermit I know that the NVIDIA GeForce RTX 3090 have previous given us some trouble by given a different result than other hardware, but we never been able to narrow down what the real issue is. I know if you just google "pytorch 3090" you will see lengthy discussions about the compatibility of that card with pytorch.
> 
> For now could you also provide the output of: `nvcc --version`
> 
> to check what version of cuda you are running? Of cause it is going to be hard for me to help with debugging, since I do not have access to 3090 card.

Thanks @SkafteNicki .  The output of `nvcc --version`
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

**Comment by h2hermit** [comment]
> @h2hermit I know that the NVIDIA GeForce RTX 3090 have previous given us some trouble by given a different result than other hardware, but we never been able to narrow down what the real issue is. I know if you just google "pytorch 3090" you will see lengthy discussions about the compatibility of that card with pytorch.
> 
> For now could you also provide the output of: `nvcc --version`
> 
> to check what version of cuda you are running? Of cause it is going to be hard for me to help with debugging, since I do not have access to 3090 card.

Thanks @SkafteNicki .  The output of `nvcc --version`
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

**Comment by SkafteNicki** [comment]
That is really strange to me. I just checked a we are actually using RTC 3090 cards for our GPU testing:
https://github.com/Lightning-AI/torchmetrics/blob/d2d346c5edee436edb8f59b1a340be23135b832e/.azure/gpu-unittests.yml#L19-L32
One of them (the "old" config) is even running the same cuda version as you. The specific config is using a older version of pytorch but thats essentially the difference.

I would recommend that you try to update your cuda to v11.7 or v11.8 and then try running using the newest pytorch v2.0.
