### ISSUE TITLE
 cannot import name '_compare_version' from 'torchmetrics.utilities.imports

### ISSUE THREAD

**Issue by liguge** [Lightning-AI/torchmetrics#1923]
### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary>Code sample</summary>

</details>

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):
- Python & PyTorch Version (e.g., 1.0):
- Any other relevant information such as OS (e.g., Linux):

**Comment by SkafteNicki** [comment]
Hi @liguge, thanks for raising this issue.
`_compare_version` has been moved to https://github.com/Lightning-AI/utilities which contains many utilities functions used in all lightning products. The package is automatically installed as a dependency of `torchmetrics`.
Please update your import to
```python
from lightning_utilities.core.imports import compare_version
```
Thanks.
Closing issue.

**Comment by mxjoe35** [comment]
Ok, how do I update the import?

**Comment by name-Bing** [comment]
issue has been worked out
