### ISSUE TITLE
CLIPScore demo code is incorrect

### ISSUE THREAD

**Issue by IanMaquignaz** [Lightning-AI/torchmetrics#1942]
Page: [CLIPScore](https://torchmetrics.readthedocs.io/en/stable/multimodal/clip_score.html)

Demo import CLIPScore as:
```python
from torchmetrics.multimodal import CLIPScore
```

But the correct import is: 
```python
from torchmetrics.multimodal.clip_score import CLIPScore
```

**Comment by jongmin4422** [comment]
Thank you.
It was helpful to me!
