### ISSUE TITLE
Memory leak when creating multiple instances of the same metric

### ISSUE THREAD

**Issue by Yann-CV** [Lightning-AI/torchmetrics#1949]
## 🐛 Bug

Depending on the situation, one can instantiate multiple instances of the same metric, in order to evaluate different dataset or pipelines, ...

In this "one shot usage" of a metric, one would "naturally" use it like:

```
metric =Metric()
result = metric(target=target, preds=preds)
```

Or alternatively:
```
metric = Metric()
metric.update(target=target, preds=preds) (xmultiple times)
metric.compute()
```

The reset call (which we know is the good practice) can look like not mandatory in that case because the metric will only be ran once.

In that situation, we have noticed a memory leak with some states of the metric not freed within the GPU memory. This memory leak is at least present for 4 metrics we have tested: BinaryAUROC, BinaryAveragePrecision, BinaryROC, BinaryPrecisionRecallCurve.

Depending on the size of your datasets and your computing machine, this can end up with GPU crash:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 194.00 MiB (GPU 0; 10.92 GiB total capacity; 9.63 GiB already allocated; 87.38 MiB free; 10.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

This issue looks like similar like:
- https://github.com/Lightning-AI/torchmetrics/issues/482
- https://github.com/Lightning-AI/torchmetrics/issues/1190
- https://github.com/Lightning-AI/torchmetrics/issues/1160

### To Reproduce

```
import numpy as np
import torch
from torchmetrics.classification.precision_recall_curve import BinaryPrecisionRecallCurve

DEVICE = torch.device("cuda")

preds = np.random.uniform(0, 1, (10, 1, 30, 30))
target = np.zeros_like(preds, dtype=int)
target[:, :, 5:15, 5:15] = 1

preds = torch.from_numpy(preds).to(DEVICE, non_blocking=True)
target = torch.from_numpy(target).to(DEVICE, non_blocking=True)

start = torch.cuda.memory_allocated(DEVICE)

for idx_loop in range(200):
    curve = BinaryPrecisionRecallCurve()
    curve = curve.to(DEVICE, non_blocking=True)
    curve(preds=preds, target=target)
    print(f"memory at {idx_loop}: {torch.cuda.memory_allocated(DEVICE) - start}")
```

### Expected behavior

We know that the good recommended practice is to then call metric.reset() but we think:

- A bit of documentation regarding this leak could help users (especially beginners) to not make the mistake to forget the reset() call --> maybe make the documentation [even more recommend users to use the reset call would be enough](https://torchmetrics.readthedocs.io/en/stable/pages/quickstart.html)

- no more memory leak when one is not using the update+compute pipeline but directly using metric(target=target, preds=preds)

- a [specific argument allowing to automatically resetting after the compute call ](https://github.com/Lightning-AI/torchmetrics/issues/482). It is probably not as easy as it seems. Indeed, we tested to add a reset call after the compute or with an overriding of __del__ but it did not removed the memory leak...

### Environment

```
CONFIGURE_OPTS=--enable-shared pyenv install 3.11.4
pyenv virtualenv 3.11.4 torchmetrics
pyenv local torchmetrics
pip install torchmetrics
```

### Additional context

Based on this MWE, we ran some experiments by calling, after the metric computation, at each loop index either:
- `del metric`
- `gc.collect()`
- `curve.reset()`

For each of these settings, we plotted the memory allocated for each index and for each type of cleaning: 
![mem_leak_roc](https://github.com/Lightning-AI/torchmetrics/assets/54800486/fc432e14-2d20-488f-ace7-c6b5c8525c1d)
![mem_leak_auroc](https://github.com/Lightning-AI/torchmetrics/assets/54800486/93b2fc54-dd84-4a60-85de-0b209785f360)
![mem_leak_prcurve](https://github.com/Lightning-AI/torchmetrics/assets/54800486/8b5af30b-b6b6-402b-9ca3-598b570d3ed3)
![mem_leak_ap](https://github.com/Lightning-AI/torchmetrics/assets/54800486/693fb6a8-7b7b-4f65-8142-ed5b1c7883f3)

**Comment by SkafteNicki** [comment]
Hi @Yann-CV, thanks for raising this issue.

I am more than open to improve our documentation, but this "one-shot" usecase have always seem strange to me.
If you are only interested in one-shot then why are you not using the functional version of each metric e.g.
```python
# use
res = binary_precision_recall_curve(preds, target)
# instead of
metric = BinaryPrecisionRecallCurve()
res = metric(preds, target)
```
functionals does not have any internal states and should therefore not be leaking any memory regardless of how many times they are called.

**Comment by SkafteNicki** [comment]
@Yann-CV Alright, I think I better understand your usecase and why you run into these problems.

We have in the past investigated this issue and for metrics where the state is a list (which it is for some of the metrics you have mentioned) it is very hard for us to control the memory freeing because the internal state is a python object and therefore controlled by the garbage collector in python. 

I would be completely fine with adding a `Metric and memory` section to this page: 
https://torchmetrics.readthedocs.io/en/stable/pages/overview.html

If you could give a proposal what you want to be mentioned in such a section that would be great :)

**Comment by Yann-CV** [comment]
@SkafteNicki , I guess I would go for something like:

Torchmetrics allows to compute performance metrics during either training and evaluation of models. 
Those metrics are as much as possible designed to be both memory (batch update, binned computation) and timely (GPU leverage) efficient for any input type (image, sound, ...) and dataset (even really big ones). 

Depending on the situation, all Torchmetrics' metric can be accessed in 2 different ways:
 
- Create a metric instance and call either:

```
metric = PrecisionRecallCurve()
metric.update(target, preds)
result = metric.compute()
metric.reset()
```

or 

```
metric = Metric()
result = metric(target, preds)
metric.reset()
```

The metric classes are really useful during training of model or when you need to deal with big datasets (see documentation for more details). 

Warnings: 
- If you do not call the reset method, the python garbage collector can struggle to totally clean the gpu states.
This can result in a memory leak when you create multiple instances of the same metric for different purposes in the same software.
- When the number of points to evaluate is high, it is advised to make `update` calls sequentially on data batch.


- Call functional functions directly:

`result = binary_precision_recall_curve(preds, target)`

The functional function are not managing any internal state. Thus, they can be used when the iterative metric computation is not required, for instance when the metric internal state evolution is not used elsewhere or when evaluating small datasets.

**Comment by SkafteNicki** [comment]
Hi @Yann-CV thanks for the proposal, I will try to incorporate it into section about memory management in TM :]
