### ISSUE TITLE
Fixes needed for docs

### ISSUE THREAD

**Issue by lantiga** [Lightning-AI/torchmetrics#1962]
## 📚 Documentation

- [x] All the links originating from this page lead to 404: https://torchmetrics--1956.org.readthedocs.build/en/1956/pages/all-metrics.html

- [x] Plots (eg for mean, but it's also for all the others) are preceded by a `(,,,)` string that is unclear <img width="261" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/191033/a27b84f6-1917-4392-be6b-811b7161e5ee">
  Fixed by #1965 

- [ ] Missing line break before last `pip install`: https://torchmetrics--1956.org.readthedocs.build/en/1956/audio/speech_reverberation_modulation_energy_ratio.html

- [x] AUROC docstring has formatting issues (way too many spaces between square brackets etc (this is also true for a number of other pages, like Average Precision): <img width="721" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/191033/6c236cd3-f2c0-4043-8b11-b0b42c882ff3">
  Fixed by https://github.com/Lightning-AI/torchmetrics/pull/1963

Broken links to assets:

<details>
  <summary>samples</summary>

- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/audio/signal_noise_ratio.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/accuracy.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/cosine_similarity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/auroc.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/average_precision.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/calibration_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/cohen_kappa.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/dice.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/f1_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/fbeta_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/hamming_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/hinge_loss.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/jaccard_index.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/precision.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/precision_at_fixed_recall.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/precision_recall_curve.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/recall.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/recall_at_fixed_precision.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/roc.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/specificity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/classification/specificity_at_sensitivity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/detection/mean_average_precision.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/detection/modified_panoptic_quality.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/detection/panoptic_quality.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/frechet_inception_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/inception_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/kernel_inception_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/mifid.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/peak_signal_noise_ratio.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/image/peak_signal_to_noise_with_block.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/multimodal/clip_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/nominal/cramers_v.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/nominal/fleiss_kappa.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/nominal/pearsons_contingency_coefficient.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/nominal/theils_u.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/nominal/tschuprows_t.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/pairwise/cosine_similarity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/pairwise/euclidean_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/pairwise/linear_similarity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/pairwise/manhattan_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/pairwise/minkowski_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/concordance_corr_coef.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/cosine_similarity.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/explained_variance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/kendall_rank_corr_coef.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/kl_divergence.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/log_cosh_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/mean_absolute_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/mean_absolute_percentage_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/mean_squared_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/mean_squared_log_error.html
- [ ] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/minkowski_distance.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/pearson_corr_coef.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/r2_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/rse.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/spearman_corr_coef.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/symmetric_mean_absolute_percentage_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/tweedie_deviance_score.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/regression/weighted_mean_absolute_percentage_error.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/text/match_error_rate.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/text/word_error_rate.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/text/word_info_lost.html
- [x] https://torchmetrics--1956.org.readthedocs.build/en/1956/text/word_info_preserved.html

</details>

**Comment by Borda** [comment]
broken links in https://torchmetrics.readthedocs.io/en/latest/pages/all-metrics.html are related to #1930 need to find way to update gallery :(

**Comment by Borda** [comment]
> * Plots (eg for mean, but it's also for all the others) are preceded by a `(,,,)` string that is unclear

@SkafteNicki mind checking this one? 🐰

**Comment by Borda** [comment]
> Broken links to assets:

this seems to be just PR rendering issue with latex as on the latest as well as old `0.11.0` are fine

**Comment by Borda** [comment]
> * AUROC docstring has formatting issues (way too many spaces between square brackets etc (this is also true for a number of other pages, like Average Precision):

this seems to be an annotation issue as some from the `typing` package are missing, so could be resolved in #1916

**Comment by lantiga** [comment]
@Borda @SkafteNicki checked all links, looks good!

Nit: can you check the formula for the Minkowski distance? It breaks up for me https://lightning.ai/docs/torchmetrics/stable/regression/minkowski_distance.html

<img width="132" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/191033/9bb10992-3afd-4eb7-bb48-d8bb7369de04">

**Comment by SkafteNicki** [comment]
> @Borda @SkafteNicki checked all links, looks good!
> 
> Nit: can you check the formula for the Minkowski distance? It breaks up for me https://lightning.ai/docs/torchmetrics/stable/regression/minkowski_distance.html
> 
> <img width="132" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/191033/9bb10992-3afd-4eb7-bb48-d8bb7369de04">
> 

Yes let me figure out what is wrong with that. @lantiga could you also be more specific about the missing line break regarding the `pip install` mentioned above, because it looks fine on my end.

**Comment by lantiga** [comment]
Thank you @SkafteNicki , this is what I get on my browser

<img width="989" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/191033/f54a80fb-caca-43ed-8f7c-8f6742981092">

**Comment by lantiga** [comment]
@SkafteNicki looks like it's a Safari thing

**Comment by lantiga** [comment]
looks good on Chrome, probably not worth getting too crazy about it
let's only fix the Minkowski formula and we're good @Borda
