### ISSUE TITLE
Warning message if number of detections exceeds default max_detection_threshold settings. 

### ISSUE THREAD

**Issue by jonas-amme** [Lightning-AI/torchmetrics#1974]
## 🚀 Feature

I request to add a simple warning message to the user when the number of detections exceeds the default max_detection_threshold. 

### Motivation

Especially when working with larger images in a medical context, where image dimensions can easily exceed 2k x 2k and contain a large number of cells, it is quite common that the number of detections per image exceeds the default setting of 100 detections when evaluating the entire image. If the max_detection_threshold parameter is not set correctly for this case, a large proportion of the detections will not be evaluated, dramatically affecting performance. 

### Pitch

Warning("The number of detections exceeds the default max_detection_threshold of 100 detections per frame. This may have an undesirable impact on performance. Please consider adjusting the max_detection_threshold to suit your use case.") 

### Additional context

The following output shows a small example where I used the predictions for the targets as well. So map_50 should always be 1. I used the predictions from an increasing image size. As soon as the number of detections on the image exceeds 100, the map_50 starts to decrease. If the user is not aware of the default setting, this may cause some problems. 

Image size:    200 200
No. trues:     12
No. preds:     12
map_50:        1.0
########################################
Image size:    400 400
No. trues:     59
No. preds:     59
map_50:        1.0
########################################
Image size:    600 600
No. trues:     106
No. preds:     106
map_50:        0.9405940771102905
########################################
Image size:    800 800
No. trues:     162
No. preds:     162
map_50:        0.6138613820075989
########################################
Image size:    1000 1000
No. trues:     228
No. preds:     228
map_50:        0.4356435537338257
########################################
Image size:    1200 1200
No. trues:     322
No. preds:     322
map_50:        0.31683167815208435
########################################

**Comment by SkafteNicki** [comment]
Hi @jonas-amme, thanks for raising this issue.
Just to be sure you are refering to `MeanAveragePrecision` in this issue right? No other metric have a argument that called `max_detection_threshold`, so I assume it is this metric.

**Comment by jonas-amme** [comment]
Hi @SkafteNicki , sorry for not mentioning the metric, but yes exactly, that is the metric I was referring to.

**Comment by SkafteNicki** [comment]
Hi @jonas-amme, thanks for the clarification.
I created PR #1978 with your proposal. Please take a look and confirm it looks good :]
