### ISSUE TITLE
Add Hausdorff distance as a new classification metric

### ISSUE THREAD

**Issue by rabinadk1** [Lightning-AI/torchmetrics#1990]
## 🚀 Feature

Add Hausdorff distance as a new classification metric.

### Motivation

Hausdorff distance measures how far two subsets of a metric space are from each other. Informally, two sets are close in the Hausdorff distance if every point of either set is close to some end of the other set. The Hausdorff distance is the longest distance you can be forced to travel by an adversary who chooses a point in one of the two sets, from where you then must travel to the other set. In other words, it is the greatest of all the distances from a point in one set to the closest point in the other set. More on: https://en.wikipedia.org/wiki/Hausdorff_distance

### Pitch

Haussdorff distance is an important metric to find the smoothness of the predicted segmentation map. It is widely used for segmenting medical images.

### Alternatives

We can find the following implementations in other libraries.

1. Scikit Image: https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.hausdorff_distance
2. Scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.directed_hausdorff.html
3. MONAI: https://docs.monai.io/en/latest/_modules/monai/metrics/hausdorff_distance.html

**Comment by matsumotosan** [comment]
@SkafteNicki I can take a look at this to get started on the segmentation related metrics.

**Comment by SkafteNicki** [comment]
Hi @matsumotosan, i will assign it to you :]
