### ISSUE TITLE
`higher_is_better` is not set on some classification metrics

### ISSUE THREAD

**Issue by tanhevg** [Lightning-AI/torchmetrics#2026]
## 🐛 Bug

There are some classification metrics, such as `BinaryAUROC` or `BinaryAveragePrecision`, where `higher_is_better` is not set, i.e. equal to `None`. There could be others, I have not checked all of them. 

### To Reproduce

```python
import torchmetrics as tm
auroc = tm.classification.BinaryAUROC()
assert auroc.higher_is_better
```

### Expected behavior

`auroc.higher_is_better` in the above snippet should be `True`

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.11.4, conda
- Python & PyTorch Version (e.g., 1.0): python 3.9.16, pytorch 2.0.1
- Any other relevant information such as OS (e.g., Linux): MacOS Ventura 13.4.1, Apple M2 Pro

**Comment by PierreOreistein** [comment]
Seems the same problem also exists for: BinaryRecallAtFixedPrecision

Config: Python3.11, torchmetrics 1.4.0.post0

**Comment by Borda** [comment]
@PierreOreistein mind send a PR fixing it?
