### ISSUE TITLE
403 link served on torch index url

### ISSUE THREAD

**Issue by ddelange** [Lightning-AI/torchmetrics#2076]
## 🐛 Bug

Hi 👋

```
pip install torch torchmetrics~=1.0.0 --extra-index-url https://download.pytorch.org/whl/cu118
```

Will attempt to download torchmetrics 1.0.3 from the torch index:
https://download.pytorch.org/whl/torchmetrics

The link hosted there will respond with 403 forbidden.

Could you remove that link?

Many thanks!

**Comment by Borda** [comment]
Hello, I think the the problem is using `--extra-index-url` so you shall use `--find-links` so your command will be:
```bash
apt update && \
apt install python3.7 python3-pip -y && \
pip3 install --upgrade pip && \
python3.7 -m pip install pytorch-lightning \
	--find-links=https://download.pytorch.org/whl/cu113/
```

**Comment by ddelange** [comment]
Hi @Borda, torch deprecated `--find-links`, also the official installation page now references `--index-url` / `--extra-index-url`.

`--find-links` still works if you point to a html page that contains `<a>` html tags pointing _directly_ to wheels, so that would be

```
pip install torch torchvision \
  --find-links https://download.pytorch.org/whl/cu113/torch/ \
  --find-links https://download.pytorch.org/whl/cu113/torchvision/
```

Since they now host a PyPI index, installation options for end users have become more flexible. See for instance discussions at https://github.com/ray-project/ray/pull/26072/

**Comment by ddelange** [comment]
The culprit link hosted on the torch index is https://download.pytorch.org/whl/torchmetrics-1.0.3-py3-none-any.whl

which will be preferred over torchmetrics 1.0.3 hosted on official PyPI, regardless wether the torch index is specified under `--index-url` or `--extra-index-url`.

**Comment by ddelange** [comment]
Do you have the capability to get that link removed from the torch index?

**Comment by Borda** [comment]
> Do you have the capability to get that link removed from the torch index?

We do not have any power over this index, please follow on official PyTorch issue... :(

**Comment by ddelange** [comment]
OK:) done, ty for the quick reply
