### ISSUE TITLE
Discoverability of the wrappers 

### ISSUE THREAD

**Issue by OmerShubi** [Lightning-AI/torchmetrics#2079]
Thank you for a very helpful package!
A few suggestions to improving the discoverability of the wrappers - 

After reading this documentation section

https://github.com/Lightning-AI/torchmetrics/blob/99d6d9d6ac4eb1b3398241df558604e70521e6b0/docs/source/pages/lightning.rst?plain=1#L52-L58

in the [TorchMetrics in PyTorch Lightning](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html) section, I was left feeling like I had to deal with logging tensors manually. 

However, in some cases, such as multiclass metrics with `average=None`, the [Classwise wrapper](https://torchmetrics.readthedocs.io/en/stable/wrappers/classwise_wrapper.html) can come in handy!

Suggestion for the docs - add a reference to this wrapper, and maybe to others, from the TorchMetrics in PyTorch Lightning documentation page. 

In general, I didn't see any reference to the wrappers (including from the Structure Overview page), which I think is a shame as they can be very useful. 
On this matter the MetricCollection seems similar to the other wrappers, so maybe reference the other wrappers from [that section?](https://torchmetrics.readthedocs.io/en/stable/pages/overview.html#metriccollection)

Also, in the side menu, the Wrappers section seems like just another class of metrics, but that is not the case. Suggestion - rename the section to Metric Wrappers or something like that to distinguish it from the metrics.

**Comment by Borda** [comment]
cc: @lantiga, suggestions? :flags:
