### ISSUE TITLE
Behavior of classification metrics changed in stable version and not well-documented

### ISSUE THREAD

**Issue by ding3820** [Lightning-AI/torchmetrics#2113]
Hi,

I've been using v0.11.4 for a while and I've noticed that there are subtle changes in the most of classification metrics in the stable version. 
For example, `MulticlassF1Score`, see the following code:

``` python
import torch
from torchmetrics.classification import F1Score
m = F1Score(task="multiclass", num_classes=2, average="macro", multidim_average='samplewise')
a = torch.rand(10, 2)
t = torch.ones(10, dtype=torch.long)
m(a, t)
```
and this raises an error message
```
ValueError: If `preds` have one dimension more than `target`, the shape of `preds` should  atleast 3D when multidim_average is set to `samplewise`
```
but if I make a slight modification as below, it works like I expect. But why? Why do I have to expand an extra dimension here? Usually everyone flatten their output logits in classification task, doesn't it?

``` python
a = torch.rand(10, 2, 1)
t = torch.ones((10, 1), dtype=torch.long)
m(a, t)
```

There's no such error in v0.11.4 and the document seems pretty much the same. I don't understand why this condition is necessary and has to be applied in the stable version.

As the docs:
![image](https://github.com/Lightning-AI/torchmetrics/assets/28510501/b018a1c7-ac26-4aef-89fd-212cd5473905)

We can see that (N, C, ..) should be the shape of `preds`. It seems that this "..." dimensions must be mandatory, not as I expect it could be ignore. Maybe you should update the docs or considering this to be bugfix or something else?

**Comment by SkafteNicki** [comment]
Hi @ding3820, thanks for raising this issue.
You are right that the behaviour changed and it should be documented (will be rectified in PR #2119). We enforce the extra dimension because all the classification metrics are really only proper defined when evaluated on multiple samples. For `samplewise` this means that the additional dimensions should be non-empty and preferably more than one element per sample. So the extra dimension is really to encourage only doing `samplewise` reduction when applicable.

**Comment by ding3820** [comment]
Hi @SkafteNicki ,

Thanks for your reply. The metrics in scikit learn provide more flexibility but they don't perform the last activation function itself. I guess this is the big difference between TorchMetrics and scikit learn. I'm not very clear how TorchMetrics handles inputs but it seems to me scikit learn is much easy to use. This is just a user feedback. Hope you don't mind.
