### ISSUE TITLE
DeprecationWarning: The distutils package is deprecated

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/torchmetrics#2121]
## 🐛 Bug

TorchMetrics still uses distutils, but distutils is deprecated.

### To Reproduce

```console
> python3 -Wall
>>> import torchmetrics
lib/python3.11/site-packages/torchmetrics/utilities/imports.py:18: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```

### Expected behavior

I would not expect TorchMetrics to still be using distutils.

### Environment

- TorchMetrics version: 1.1, 1.2, master (spack)
- Python & PyTorch Version: 3.11.4 & 2.0.1
- Any other relevant information such as OS: macOS 13.5.2

### Additional context

I also sometimes see a different error message from pytest:
```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
This gives one possible solution.

**Comment by Borda** [comment]
seems to be related to https://github.com/Lightning-AI/utilities/issues/119
@adamjstewart would you be interested in sending a fix/upgrade?
