### ISSUE TITLE
Half precision doesn't work with top_k > 1

### ISSUE THREAD

**Issue by nisyad-ms** [Lightning-AI/torchmetrics#2147]
## 🐛 Bug

When using predictions at half-precision, MulticlassAccuracy throws an error when using top_k > 1. Please see the code below:

### To Reproduce

Steps to reproduce the behavior...

```py
import torch
from torchmetrics.classification import MulticlassAccuracy

preds = torch.tensor([[1, 0, 0]]).half()
targets = torch.tensor([1])

metric = MulticlassAccuracy(num_classes=3, top_k=2)
metric(preds, targets)
metric.compute()
```

### Environment

- TorchMetrics version: 1.0.1
- Python & PyTorch Version (e.g., 1.0): 3.10 and 2.0.1

**Comment by SkafteNicki** [comment]
Most likely related issue on pytorch side:
https://github.com/pytorch/pytorch/issues/58841
