### ISSUE TITLE
requirement of lightning-utilities in whl file has no constraint <0.10.0

### ISSUE THREAD

**Issue by daniel-code** [Lightning-AI/torchmetrics#2229]
## 🐛 Bug

When directly install via pip, the constraint of lightning-utilities only be >=0.8.0. (ref Figure)

It should be `lightning-utilities >=0.8.0, <0.10.0`.

### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary>Code sample</summary>

```
$ pip install torchmetrics==1.2.0
$ pip list
lightning-utilities    0.10.0
torchmetrics           1.2.0
```

</details>

### Expected behavior

`lightning-utilities` should be `0.9.0` (<0.10.0).

```
$ pip install torchmetrics==1.2.0
$ pip list
lightning-utilities    **0.9.0**
torchmetrics           1.2.0
```

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 1.2.0
- Python & PyTorch Version (e.g., 1.0): 3.8
- Any other relevant information such as OS (e.g., Linux): Windows/Linux

### Additional context

![image](https://github.com/Lightning-AI/torchmetrics/assets/16793241/da9cdc92-f843-4a24-81a6-f4cfc4f1c3c9)

**Comment by Borda** [comment]
that is by design, please read the requirement/readme

**Comment by daniel-code** [comment]
Great! Thank you for the explanation.
