### ISSUE TITLE
CLIPImageQualityAssessment insists on prompt argument to be called 'beutiful'

### ISSUE THREAD

**Issue by spezialspezial** [Lightning-AI/torchmetrics#2243]
## 🐛 Bug

not working:
`metric = CLIPImageQualityAssessment(prompts=("beautiful",))`

working:
`metric = CLIPImageQualityAssessment(prompts=("beutiful",))`

This uses ClipVision, right? I assume it's not trained on 'beutiful' and there is just a typo in the CLIPImageQualityAssessment class

### Expected behavior

prompt 'beautiful' should be valid 

### Environment

Linux, Python 3.10.13, torch 2.1.0+cu118, pip torchmetrics 1.2.0

**Comment by SkafteNicki** [comment]
I rechecked and it was fixed in this PR: https://github.com/Lightning-AI/torchmetrics/pull/2103
That change is available in the newest release of torchmetrics v1.2.1 released today.
Closing issue.
