### ISSUE TITLE
torch 2.x image does not contain dependencies according to requirements/*.txt

### ISSUE THREAD

**Issue by ywchan2005** [Lightning-AI/torchmetrics#2261]
## 🐛 Bug

In `.azure/gpu-integrations.yml`, two different images are used for torch 1.x and 2.x
- torch 1.x: `pytorchlightning/torchmetrics:ubuntu22.04-cuda11.8.0-py3.9-torch1.13`
- torch 2.x: `pytorch/pytorch:2.1.1-cuda12.1-cudnn8-runtime`

The image used in torch 1.x is built from `dockers/ubuntu-cuda/Dockerfile` and all required dev packages listed in `requirements/_devel.txt` are installed in advance

However, the image used in torch 2.x is a vanilla pytorch image which contains no dev packages required to build and test torchmetrics. As a result, even if a package is added in the corresponding `.txt` file in `requirements` directory, the image does not pick up the change and fails the build and check

### To Reproduce

In my case,
1. add a new package in a `.txt` file under `requirements` directory
1. update the pull request to trigger the integration check which depends on torch 2.x image

<details>
  <summary>Code sample</summary>

e.g. in `requirements/image.txt`, add `kornia >=0.6.7, <0.7.1`

</details>

### Expected behavior

the images install packages according to the `.txt` files in `requirements` directory

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 1.3.0dev
- Python & PyTorch Version (e.g., 1.0): 3.9.18 / 2.1.1+cu121
- Any other relevant information such as OS (e.g., Linux): Debian GNU/Linux 12 (bookworm)

**Comment by ywchan2005** [comment]
@Borda thanks for the reply. I'm in the middle of a pull request, and struggling how to move forward due to the errors raised in the integration pipeline which blocks the review process.

**Comment by Borda** [comment]
> I'm in the middle of a pull request, and struggling how to move forward due to the errors raised in the integration pipeline which blocks the review process.

Have you already opened the PR? then we can see together where the problem is...

**Comment by ywchan2005** [comment]
Here's the PR
https://github.com/Lightning-AI/torchmetrics/pull/2260
