### ISSUE TITLE
Cannot use average method 'none' in Dice meter

### ISSUE THREAD

**Issue by CielAl** [Lightning-AI/torchmetrics#2262]
## 🐛 Bug
In the docstring of
it states that `average` allows `none` or None input wherein a class-wise result will be reported. However the code here https://github.com/Lightning-AI/torchmetrics/blob/master/src/torchmetrics/classification/dice.py#L176 suggests that a ValueError will be raised and therefore `average` must be micro/macro/sample.

It appears that the value check is redundant considering the following line was added already.
```py
        if average not in allowed_average:
            raise ValueError(f"The `average` has to be one of {allowed_average}, got {average}.")

```

### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary>Code sample</summary>

</details>

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):
- Python & PyTorch Version (e.g., 1.0):
- Any other relevant information such as OS (e.g., Linux):

**Comment by Borda** [comment]
seems to be related to #2282
