### ISSUE TITLE
`dummy_image` in FID doesn't fit into custom feature extractors

### ISSUE THREAD

**Issue by asy51** [Lightning-AI/torchmetrics#2266]
## 🐛 Bug

When a custom feature extractor is passed into FID, a hard-coded `dummy_image` is used to find the number of features:
https://github.com/Lightning-AI/torchmetrics/blob/3e5a6ea49046d90574ae25151cebfe3b1d96496d/src/torchmetrics/image/fid.py#L298-L301

which will fail if the custom extractor does not accept input with dtype=`torch.uint8`, shape=`(1, 3, 299, 299)`, and device does not match the custom feature extractor.

### To Reproduce

```
import torchmetrics.image
import torchvision
torchmetrics.image.FrechetInceptionDistance(torchvision.models.resnet50().to('cuda'))
```

**Comment by Borda** [comment]
@asy51 mind sharing env detail fro reproducing the issue?

**Comment by asy51** [comment]
Python 3.10.4
torch 2.0.0+cu177
torchvision 0.15.1+cu117
torchmetrics 1.2.1
torch_fidelity 0.3.0
