### ISSUE TITLE
[BUG] AttributeError: 'Tensor' object has no attribute '_is_synced'

### ISSUE THREAD

**Issue by esnvidia** [Lightning-AI/torchmetrics#2268]
## 🐛 Bug

```
torchmetrics/metric.py:236, in Metric.forward(self, *args, **kwargs)
    229 """``forward`` serves the dual purpose of both computing the metric on the current batch of inputs but also
    230 add the batch statistics to the overall accumululating metric state.
    231 
    232 Input arguments are the exact same as corresponding ``update`` method. The returned output is the exact same as
    233 the output of ``compute``.
    234 """
    235 # check if states are already synced
--> 236 if self._is_synced:
    237     raise TorchMetricsUserError(
    238         "The Metric shouldn't be synced when performing ``forward``. "
    239         "HINT: Did you forget to call ``unsync`` ?."
    240     )
    242 if self.full_state_update or self.full_state_update is None or self.dist_sync_on_step:

AttributeError: 'Tensor' object has no attribute '_is_synced'
```

### To Reproduce

Steps to reproduce the behavior...

running example code in pytorch-forecasting: https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/stallion.html

```py
# find optimal learning rate
res = Tuner(trainer).lr_find(
    tft,
    train_dataloaders=train_dataloader,
    val_dataloaders=val2_loader,
    max_lr=10.0,
    min_lr=1e-6,
)

print(f"suggested learning rate: {res.suggestion()}")
fig = res.plot(show=True, suggest=True)
fig.show()
```

<details>
  This looks like an error where `self` is a tensor and not the class

### Environment

installed via poetry. Checkout pytorch-forecasting v0.10.3 branch or newer. Checked on pytorch lightning 1.7.4 and >=2.0

torchmetrics v1.2.1

**Comment by Borda** [comment]
@esnvidia could you update also what Tm version you are using?

**Comment by esnvidia** [comment]
Added

**Comment by SkafteNicki** [comment]
Hi @esnvidia, thanks for reporting this issue.
I am unable to reproduce the error with the example code, everything runs fine for me:
https://drive.google.com/file/d/1FQZcEceTdyud_c9KPl9WcOFSzwNxwU9M/view?usp=sharing
could you provide the full traceback for the error you are seeing just to get a better idea where it is happening.
