### ISSUE TITLE
Missing `CompositionalMetric` class in the __init__.py file

### ISSUE THREAD

**Issue by MarylineChen** [Lightning-AI/torchmetrics#2269]
## 🐛 Bug

The `CompositionalMetric` class in metric.py can't be imported or used directly because it's not included in the __init__.py file.

### To Reproduce
```
from torchmetrics import CompositionalMetric
```

Error message:
```
ImportError: cannot import name 'CompositionalMetric' from 'torchmetrics' ([...]/lib64/python3.9/site-packages/torchmetrics/__init__.py)
```

### Expected behavior

`CompositionalMetric` should be importable without any issues.

### Environment
```
torchmetrics==1.2.1
```

**Comment by Borda** [comment]
@MarylineChen that is a good observation; mind sharing why would you need or expect to find it in TM root?

**Comment by MarylineChen** [comment]
My use case is pretty simple. I'm implementing some metrics using TM where I have three classes: class A(Metric), class B(Metric) and class C(?) which is an operation over class A and B, and it seems CompositionMetric is the good class to inherit, so I would like to do class C(CompositionMetric).

**Comment by Borda** [comment]
> so I would like to do class C(CompositionMetric)

sire so you can simply do `from torchmetrics.metric import CompositionMetric`

**Comment by MarylineChen** [comment]
True, that could be enough :)

**Comment by SkafteNicki** [comment]
Yeah, `CompositionalMetric` is not really meant to be used directly by users like inherit from it.
Instead it will always be the result when composing two other metrics:
```python
A = MetricClassA()
B = MetricClassB()
C = A + B
print(isinstance(C, CompositionalMetric))  # True
```
it is more an internal class. For this reason, I do not think we should expose it in the root `__init__.py` and users that really want to use it can just import as
```python
from torchmetrics.metric import CompositionMetric
```
Closing issue.
