### ISSUE TITLE
Single recall score for all images

### ISSUE THREAD

**Issue by colaber2** [Lightning-AI/torchmetrics#2271]
Hello,

Is there a way to get a single recall score for all the images?
Because when I use MeanAveragePrecision class with extended_summary=True it gives multiple values, similar to the following:

`'recall': tensor([[[[0.2922, 0.8148, 0.8148], [0.1226, 0.6415, 0.6415], [0.3920, 0.9440, 0.9440], [0.7500, 1.0000, 1.0000]]]], dtype=torch.float64)}`

Thank you so much in advance.

**Comment by SkafteNicki** [comment]
Hi @colaber2, the `recall` output is described in documentation
https://lightning.ai/docs/torchmetrics/stable/detection/mean_average_precision.html
> recall: a tensor of shape (TxKxAxM) containing the recall values. Here T is the number of IoU thresholds, K is the number of classes, A is the number of areas and M is the number of max detections per image.

In most cases the `A` corresponds to the number of images in your dataset. Therefore, if you are just interested in a overall recall value then doing:
```python
result = metric.compute()
recall = result["recall"]
print(recall.mean())
```
if you want the score per image then:
```python
result = metric.compute()
recall = result["recall"]
print(recall.mean(dim=[0, 1, 3]))
```
