### ISSUE TITLE
Dice metric cannot compute DICE score for each class

### ISSUE THREAD

**Issue by NguyenAnhTien** [Lightning-AI/torchmetrics#2282]
## 🐛 Bug

The class DICE (in the dice.py), at the line 176, the condition

```
if average not in ["micro", "macro", "samples"]
```

doest not work with the documents. This condition does not allow 'none' (None) value for the class DICE. Therefore, this class cannot produce DICE for each class.

**Comment by Borda** [comment]
I guess you are referring to the master branch, right?
Pls add a link to the code; that would be easier... :flamingo:

**Comment by NguyenAnhTien** [comment]
I figured out the problem in this version

[https://github.com/Lightning-AI/torchmetrics/blob/v1.2.1/src/torchmetrics/classification/dice.py#L31-L288](https://github.com/Lightning-AI/torchmetrics/blob/v1.2.1/src/torchmetrics/classification/dice.py#L31-L288)

**Comment by asbjrnmunk** [comment]
Duplicate issue: https://github.com/Lightning-AI/torchmetrics/issues/1602
