### ISSUE TITLE
error while running in SLURM-managed cluster

### ISSUE THREAD

**Issue by kartikey-chhipa** [Lightning-AI/torchmetrics#2300]
### To Reproduce

run any code with multiple gpus.

sbatch submission parameters 
```
#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --gres=gpu:6
#SBATCH --ntasks-per-node=96
#SBATCH --time=99:00:00
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out
```
have to give ntasks-per-node=96 as it is mandatory to allocate 16 cores CPU to each GPU, I cannot keep the Trainer(devices=6), gres=gpu:6, ntasks-per-node=6

In the trainer
```py
trainer = pl.Trainer(
        max_epochs=NUM_EPOCHS,
        **devices=6**,
        num_nodes = 1,
        accelerator="auto"
        accumulate_grad_batches=5,
        callbacks= [early_stopping, model_checkpoint],
        logger=logger
    )
```
<details>
  <summary> Error</summary>
```
[rank: 0] Global seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/96
slurmstepd: error: *** JOB 168885 ON scn67-10g CANCELLED AT 2023-08-31T18:04:42 ***
```
output logs: 
```
Running on hosts: scn67-10g
Running on 1 nodes.
Running 96 tasks.
Job id is 168885
```
</details>

### Expected behavior

I want to utilize multiple gpus while allocating 16 core cpus for each gpus.

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): pip
- Python & PyTorch Version (e.g., 1.0): Python 3.9.17, torch version '2.1.0+cu118'
- Any other relevant information such as OS (e.g., Linux): Linux

**Comment by Borda** [comment]
I guess you are using the latest version of TM, right?

**Comment by kartikey-chhipa** [comment]
> I guess you are using the latest version of TM, right?

yes, using latest version of PL v2.1.0.rc0, and this is not specific to TM (apologies for the confusion.)
