### ISSUE TITLE
SSIM AttributeError when reduction='none'

### ISSUE THREAD

**Issue by Miles629** [Lightning-AI/torchmetrics#2317]
## 🐛 Bug

  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torchmetrics/image/ssim.py", line 146, in update
    self.similarity.append(similarity)
AttributeError: 'Tensor' object has no attribute 'append'

### To Reproduce
```python
import torchmetrics
patch_list = torch.randint(0,255,(4,3,128,128)).float().cuda()
gt_list = torch.randint(0,255,(4,3,128,128)).float().cuda()
torchmetrics_ssim = torchmetrics.StructuralSimilarityIndexMeasure(data_range=1.0).cuda()
torchmetrics_ssim.reduction='none'
ssim = torchmetrics_ssim(patch_list,gt_list)#both of them with tensor shape of [4,3,128,128]
```
### Expected behavior

The return value should be a tensor with shape = batchsize (4 in the example)
represents 4 batches ssim value

### Environment
torch                          2.0.0
torchmetrics                   0.11.4
Python 3.8.17

**Comment by Miles629** [comment]
I update torchmetrics to torchmetrics-1.3.0.post0 and the error still exist.

  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torchmetrics/metric.py", line 303, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torchmetrics/metric.py", line 372, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torchmetrics/metric.py", line 465, in wrapped_func
    update(*args, **kwargs)
  File "/root/miniconda3/envs/ngpnew/lib/python3.8/site-packages/torchmetrics/image/ssim.py", line 156, in update
    self.similarity.append(similarity)
AttributeError: 'Tensor' object has no attribute 'append'

**Comment by SkafteNicki** [comment]
Hi @Miles629, thanks for reporting this issue.
This happens because you are directly setting the `reduction` attribute *after* initialization instead of providing it as an argument.
Your code should therefore just be
```python
import torchmetrics
import torch
patch_list = torch.randint(0,255,(4,3,128,128)).float().cuda()
gt_list = torch.randint(0,255,(4,3,128,128)).float().cuda()
torchmetrics_ssim = torchmetrics.StructuralSimilarityIndexMeasure(data_range=1.0,reduction='none').cuda()
ssim = torchmetrics_ssim(patch_list,gt_list)
```
The reason for this being that the states which are used doing metric calculations are initialized in `__init__` and therefore setting the `reduction` attribute after leads to errors later.
https://github.com/Lightning-AI/torchmetrics/blob/a68455afb9041d1d32c1d6546897fee416abdc41/src/torchmetrics/image/ssim.py#L101-L116

Closing issue.
