### ISSUE TITLE
`MetricCollection` does not share internal `state`

### ISSUE THREAD

**Issue by weihua916** [Lightning-AI/torchmetrics#2324]
## 🐛 Bug

When I use `MetricCollection` to group auroc metrics with different `average` mode (which should share the same `metric_state`), the underlying `metric_state` is not shared.

### To Reproduce

```python
import torch
from torchmetrics import MetricCollection, AUROC
m = MetricCollection({'macro': AUROC(task='multilabel', average = 'macro', num_labels=100), 'micro': AUROC(task='multilabel', average = 'micro', num_labels = 100)})
pred = torch.randn(10, 100)
target = torch.randint(0, 2, (10, 100))
m.update(pred, target)
print(m['micro'].metric_state['preds'][0].data_ptr()) # e.g., 5728237568
print(m['macro'].metric_state['preds'][0].data_ptr()) # e.g., 5728230400
print(m.compute()) # {'macro': tensor(0.5295), 'micro': e.g., tensor(0.5129)}
```

### Expected behavior
`m['micro'].metric_state['preds'][0].data_ptr()` and `m['macro'].metric_state['preds'][0].data_ptr()` should be the same, since the internal state is shared.

### Environment

- TorchMetrics version: `v1.3.0.post0` (`pip` installed)
- Python & PyTorch Version: Python 3.10.13 `torch==2.1.1`
- Any other relevant information such as OS: Linux

**Comment by rusty1s** [comment]
I think this works as expected since it looks like `__getitem__` will copy the state by default: https://github.com/Lightning-AI/torchmetrics/blob/master/src/torchmetrics/collections.py#L540

Running
```python
import torch
from torchmetrics import AUROC, MetricCollection

m = MetricCollection({
    'macro':
    AUROC(task='multilabel', average='macro', num_labels=4),
    'micro':
    AUROC(task='multilabel', average='micro', num_labels=4)
})
pred = torch.randn(2, 4)
target = torch.randint(0, 2, (2, 4))
m.update(pred, target)
m.update(pred, target)
print(m.__getitem__('micro', False).preds[1].data_ptr())
print(m.__getitem__('macro', False).preds[1].data_ptr())
```
yields the expected result.

**Comment by weihua916** [comment]
I see. Good catch! Did now know there is copying.
