### ISSUE TITLE
Broken source links in documentation of `1.3.0.post0`

### ISSUE THREAD

**Issue by ValerianRey** [Lightning-AI/torchmetrics#2331]
## 📚 Documentation

The part of the link that is bugged is generated in [`conf.py`](https://github.com/Lightning-AI/torchmetrics/blob/v1.3.0.post/docs/source/conf.py) by the function:
```python
def _get_version_str():
    if any(s in torchmetrics.__version__ for s in ("dev", "rc")):
        version_str = "master"
    else:
        version_str = f"v{torchmetrics.__version__}"
    return version_str
```

This function assumes that `torchmetrics.__version__`  (from [`__about__.py`](https://github.com/Lightning-AI/torchmetrics/blob/v1.3.0.post/src/torchmetrics/__about__.py)) is the same as the tag name, except for a "v" prefix in the tag name (that `_get_version_str` adds, as you can see on the code I displayed above).

The problem here is that `torchmetrics.__version__` is `"1.3.0.post0"` and the tag name is `v1.3.0.post` instead of `v1.3.0.post0`.

The generated links thus end up with the additional "0" in them, which leads to a 404 error.

**Comment by Borda** [comment]
I think the code is fine and my wrong with naming the git tag, I shall be more vigilant... so created a new tag with the same commit SHA.

**Comment by ValerianRey** [comment]
Yep it works now, thanks for the fix :)
