### ISSUE TITLE
Add Support for SQ and RQ in Panoptic Quality

### ISSUE THREAD

**Issue by ChristophReich1996** [Lightning-AI/torchmetrics#2380]
## 🚀 Feature

First of all thanks for implementing the Panoptic Quality (PQ) metric. However, the current PQ implementation only computes the PQ. The Segmentation Quality (SQ) and Recognition Quality (RQ) are not computed. It would be amazing to have an option to also compute these metrics within the PQ implementation.

### Motivation

Almost all papers (_e.g._, [U2Seg](https://arxiv.org/pdf/2312.17243.pdf)) report the PQ alongside SQ and RQ so extending the PQ implementation to also compute SQ and RQ would be amazing.

### Alternatives

We could also implement both SQ and RQ as separate metrics, however, since I'm not aware of any work reporting SQ or RQ w/o PQ this would be somewhat inconvenient. This would also lead to an additional compute overhead.

**Comment by SkafteNicki** [comment]
Hi @ChristophReich1996, thanks for raising this issue.
Do you have a reference for how the the SQ and RQ is defined?

**Comment by ChristophReich1996** [comment]
Hi @SkafteNicki, we could just use the already computed IoU, TP, FN, and FP to also compute both SQ and RQ. We can just follow the equation from the [original paper](https://arxiv.org/pdf/1801.00868.pdf):

<img width="643" alt="Screenshot 2024-02-14 at 11 13 25" src="https://github.com/Lightning-AI/torchmetrics/assets/34400551/0a1c0abc-15ea-4b4d-9623-7fc4681d8518">

We would just need to change this function:

https://github.com/Lightning-AI/torchmetrics/blob/afae59e4d75ef2dfd0023e3a665e46a0a62833a5/src/torchmetrics/functional/detection/_panoptic_quality_common.py#L447-L469

Additionally, it was already discussed somewhere, but I guess it would be beneficial to compute PQ, SQ, and RQ on a per-class level as well as the global average.

**Comment by SkafteNicki** [comment]
@ChristophReich1996 thanks for the info. Yeah that should be pretty easy to add/modify in the current codebase. Only thing to consider is how we should go about backwards compatibility. I agree that it does not make sense to separate out the individual scores into different metrics.
Also returning the score per-class level could most likely also be something that is easy to add to the metric while we are refactoring it.

**Comment by ChristophReich1996** [comment]
@SkafteNicki Yeah backward compatibility could be somewhat cumbersome. But I guess having some flag could get us backward compatibility. Let me quickly draft a pull request.
