### ISSUE TITLE
Error in ERGAS metric

### ISSUE THREAD

**Issue by Andrewwango** [Lightning-AI/torchmetrics#2416]
In the definition of ERGAS, it should be `\ ratio` rather than `* ratio` 

For example see ERGAS defined in [Du et al](https://ieeexplore.ieee.org/abstract/document/4317530), [Meng et al](https://ieeexplore.ieee.org/document/9082183)

https://github.com/Lightning-AI/torchmetrics/blob/4230cfef3d2020fffff873565acea01ad883d3e4/src/torchmetrics/functional/image/ergas.py#L82

**Comment by SkafteNicki** [comment]
Hi @Andrewwango, thanks for raising this issue.
I do not agree that there is an error in our formulation. If you look at the original paper by [Wald](https://minesparis-psl.hal.science/hal-00464703/document) (page 163 in the pdf) you will see that ERGAS metric is defined by multiplying the fraction and not dividing it. If you look at the paper by [Du et al](https://www.researchgate.net/publication/3449922_On_the_Performance_Evaluation_of_Pan-Sharpening_Techniques) that you refer to, in equation (1) they ERGAS metric they multiply the ratio `h/l`. I am not sure why it is different in the paper by Meng et al.

I am updating the metric to reference the original paper and the specific formula we are using for calculating the metric in #2426

**Comment by Andrewwango** [comment]
I disagree @SkafteNicki . The Wald and Du papers multiply by the _ratio of pixel lengths_ , which is the inverse of the ratio. For example for `ratio=4` the pixel length ratio `h/l=1/4`. The Wald paper gives examples of `h/l=1/4` and `h/l=1/2`. [Azarang et al](https://arxiv.org/ftp/arxiv/papers/2102/2102.03908.pdf) states that  `h/l=1/4` for common satellites Pleiades-1A, WorldView-2, and GeoEye-1.

Therefore you should be dividing by the integer ratio. Please reopen this issue @SkafteNicki @Borda :)

**Comment by SkafteNicki** [comment]
Hi @Andrewwango, thanks for correcting me. I am not a expert on these metrics and just saw that the original paper defined it by multiplication and division. Sorry on my part.
I make sure to fix it.

**Comment by Andrewwango** [comment]
Hi, any progress on this?
