### ISSUE TITLE
Bug in ERGAS

### ISSUE THREAD

**Issue by yc-cui** [Lightning-AI/torchmetrics#2497]
## 🐛 Bug

It should be divided by the `ratio`, rather than multiplied by the `ratio`, otherwise it will amplify the correct indicator by the square of the `ratio`.

https://github.com/Lightning-AI/torchmetrics/blob/ca7c8ebb7ee5ab63833cb2be4097e29b58b51b4d/src/torchmetrics/functional/image/ergas.py#L82

For reference, below is  a correct implementation by matlab:

https://github.com/liangjiandeng/DLPan-Toolbox/blob/main/02-Test-toolbox-for-traditional-and-DL(Matlab)/Quality_Indices/ERGAS.m#L32

**Comment by Mdmdma** [comment]
Hi this bug fix enables correct behavior, but now the documentation is not consistent with the source paper. In the source paper the ratio is <1 the way it is stated here it is supposed to be >1. I do not think this is a issue, but maybe noteworthy in the documentation.
