### ISSUE TITLE
Add `_filter_kwargs` in `ClasswiseWrapper` metric wrapper

### ISSUE THREAD

**Issue by ioangatop** [Lightning-AI/torchmetrics#2542]
As the `ClasswiseWrapper` accepts agnostic `*args, **kwargs` arguments, its not handy to use it in a `MetricColletion`, ass tailored input arguments for other metrics get passed in the metrics.

It would be great, just like in `MetricColletion`, to add the `_filter_kwargs` for the metric

**Comment by Borda** [comment]
> It would be great, just like in `MetricColletion`, to add the `_filter_kwargs` for the metric

sounds fine to me... what do you think @justusschock @SkafteNicki ?

**Comment by ioangatop** [comment]
Thanks a lot @SkafteNicki @stancld and @Borda 🙏
