### ISSUE TITLE
`zero_division` does not work for binary IoU (Jaccard index) calculation and returns NaN

### ISSUE THREAD

**Issue by jinggqu** [Lightning-AI/torchmetrics#2658]
## 🐛 Bug

See source code: https://github.com/Lightning-AI/torchmetrics/blob/eaa85e02a9414089d0054a16dfadaa6305ac28e8/src/torchmetrics/functional/classification/jaccard.py#L65-L70

### To Reproduce

This bug can be triggered if the predicted result and real label does not contain any foreground pixels (i.e., all zeros.), as shown in the above code, the sum of `(confmat[0, 1] + confmat[1, 0] + confmat[1, 1])` will be zero under this circumstance. 

Also, the `zero_division` parameter in the `BinaryJaccardIndex` does not take effect during `binary` task calculations, as the IoU calculations for the binary task are returned early (Line 70).

### Expected behavior

Expect special judgment on division by zero like the `_safe_divide()` method, which returns the correct value based on the `zero_division` parameter. See:

https://github.com/Lightning-AI/torchmetrics/blob/eaa85e02a9414089d0054a16dfadaa6305ac28e8/src/torchmetrics/utilities/compute.py#L46-L60

### Environment

- TorchMetrics 1.4.0.post0

**Comment by rittik9** [comment]
pls assign it to me @Borda
