### ISSUE TITLE
`higher_is_better` for `InfoLM` should change depending on `information_measure`

### ISSUE THREAD

**Issue by grahamannett** [Lightning-AI/torchmetrics#2659]
Not sure if there are other metrics this will apply to but for InfoLM, if the `information_measure` is l2, then the distance will always positive, but `infolm.higher_is_better` shows True. I am pretty sure that is no longer the case compared to the base measure which is KL in which case trending towards 0 from vals < 0 is improvement

**Comment by Borda** [comment]
That is a good point and should be fixed. Are you interested in sending a PR?
cc: @lucadiliello

**Comment by grahamannett** [comment]
Sure, will try and send a PR in the next few days.  

Was thinking/wondering if its an issue for other metrics but not sure if I will have time to go through and look into others/understand if it applies in other cases. This one specifically made some metrics for runs very confusing!

**Comment by grahamannett** [comment]
Dunno if its just me but have tried locally and vscode and seems like the devcontainer that helps set this project up isnt really usable?  Was really confused as thought there was something going on with pytest cache, realized all the devcontainer pythons are using torchmetrics from `/usr/local/lib/python3.9/site-packages` which is installed from pypi?

Is the devcontainer not what you all use?  Eventually just did editable install and then saw that maybe `make env` would have been helpful but not sure if there was some more guide I should follow for getting everything setup to dev on this project easily.

I just PR'd #2674 2674 so can probably move discussion there about the values or if there is a different way to set `higher_is_better`
