### ISSUE TITLE
GPL 2.0 License detected in `functional/text/chrf.py`

### ISSUE THREAD

**Issue by kkoehncke** [Lightning-AI/torchmetrics#2665]
Hi Team,

Our scanner is detecting the GPL-2.0 license in the src/torchmetrics/functional/text/chrf.py file. We understand this file contains code from a GPL-licensed project, however this license is incompatible with the Apache-2.0 license set on the repository, and our internal compliance standards do not allow us to use it. Would it be possible to remove or update the file in case it is not needed, please?

Thanks!

**Comment by Borda** [comment]
it was added in #641 so checking it now...
 @stancld do you remember how we addressed the license discrepancy?

**Comment by Borda** [comment]
@kkoehncke I have prepared a drop-off in #2668
But while looking at our implementation and the reference it seems to me that it differs very much as we use vectorial/tensor computing also we have split compute and update steps as is required in TM's paradigm... So I believe that @stancld as the contributor wanted to refer to the code he looked at as additional study material while implementing metrics based on [paper](https://aclanthology.org/W15-3049/).
To my knowledge, we can remove the GPL statement and mention the reference implementation in the docs.

cc: @lantiga

**Comment by lantiga** [comment]
> @kkoehncke I have prepared a drop-off in #2668 But while looking at our implementation and the reference it seems to me that it differs very much as we use vectorial/tensor computing also we have split compute and update steps as is required in TM's paradigm... So I believe that @stancld as the contributor wanted to refer to the code he looked at as additional study material while implementing metrics based on [paper](https://aclanthology.org/W15-3049/). To my knowledge, we can remove the GPL statement and mention the reference implementation in the docs.
> 
> cc: @lantiga

Nope we can't do that. It still counts as derivative work which the GPL explicitly regulates.
