### ISSUE TITLE
SSIM calculation mistake.

### ISSUE THREAD

**Issue by petertheprocess** [Lightning-AI/torchmetrics#2718]
https://github.com/Lightning-AI/torchmetrics/blob/a31417ca1bc4a47ca093c22e3f2f2b5e6843d58a/src/torchmetrics/functional/image/ssim.py#L164C1-L170C72

Before the convolution, we already applied same padding to the image
```python
        preds = F.pad(preds, (pad_w, pad_w, pad_h, pad_h), mode="reflect")
        target = F.pad(target, (pad_w, pad_w, pad_h, pad_h), mode="reflect")
```
So ssim_idx_full_image will share the same shape as original image, there is no need to take the padding out again, otherwise it will result in losing information on edge.
```python
    ssim_idx_full_image = ((2 * mu_pred_target + c1) * upper) / ((mu_pred_sq + mu_target_sq + c1) * lower)

    if is_3d:
        ssim_idx = ssim_idx_full_image[..., pad_h:-pad_h, pad_w:-pad_w, pad_d:-pad_d]
    else:
        ssim_idx = ssim_idx_full_image[..., pad_h:-pad_h, pad_w:-pad_w]
```

**Comment by petertheprocess** [comment]
Also, the `kernal_size` is a input parameter while `gauss_kernel_size` is calculated based on input parameter `sigma`. If we call the function without gaussian kernel, the padding size will still calculated based on `gauss_kernel_size` rather than `kernal_size`.
```
    gauss_kernel_size = [int(3.5 * s + 0.5) * 2 + 1 for s in sigma]

    pad_h = (gauss_kernel_size[0] - 1) // 2
    pad_w = (gauss_kernel_size[1] - 1) // 2
```

**Comment by SkafteNicki** [comment]
Hi @petertheprocess, thanks for raising this issue.
It does seem like both are errors. Feel free to create a PR correcting this :)
