### ISSUE TITLE
Maybe a new patch release?

### ISSUE THREAD

**Issue by ioangatop** [Lightning-AI/torchmetrics#2734]
### Motivation

A new release will help since there were some refactoring in the segmentation metrics. 

Thanks a lot 🙏

**Comment by Borda** [comment]
sure I can do one today :)

**Comment by SkafteNicki** [comment]
Closing as [v1.4.2](https://github.com/Lightning-AI/torchmetrics/releases/tag/v1.4.2) was released yesterday :]

**Comment by ioangatop** [comment]
hmmm that is kinda weird as the new release for example does not have the following argument from main - how is this not included 🤔 ?

https://github.com/Lightning-AI/torchmetrics/blob/fd11f337411cc44d163cf4c32e57a10bbbc93cb4/src/torchmetrics/segmentation/generalized_dice.py#L122

**Comment by ioangatop** [comment]
@Borda do you maybe know why this happen? thank you 🙏

**Comment by Borda** [comment]
> @Borda do you maybe know why this happen? thank you 🙏

what do you mean?

**Comment by ioangatop** [comment]
For example, lets get the `GeneralizedDiceScore`; on the release it seems that it has an older code from the main at that time. For example:

```
# on main; 3 weeks ago
class GeneralizedDiceScore(Metric):
    ...
    def __init__(
        self,
        num_classes: int,
        include_background: bool = True,
        per_class: bool = False,
        weight_type: Literal["square", "simple", "linear"] = "square",
        input_format: Literal["one-hot", "index"] = "one-hot",                # <-- HERE
        **kwargs: Any,
    ) -> None:
```

```
# on release 1.4.2; 2 weeks ago
class GeneralizedDiceScore(Metric):
    ...
    def __init__(
        self,
        num_classes: int,
        include_background: bool = True,
        per_class: bool = False,
        weight_type: Literal["square", "simple", "linear"] = "square",
                                                                             # <-- HERE missing arg
        **kwargs: Any,
    ) -> None:
```

**Comment by Borda** [comment]
Thanks for your concern. We have released patch release recently which by nature does not expect API changes, correct?

**Comment by ioangatop** [comment]
@Borda make sense yeah... I guess I wanted to have a minor release? and is this will be possible? :D
