### ISSUE TITLE
Docs: fix for R^2 and SMAPE

### ISSUE THREAD

**Issue by profPlum** [Lightning-AI/torchmetrics#2744]
## 📚 Documentation

SMAPE docs say: "smape [...] A tensor with non-negative floating point smape value between 0 and 1"
R^2 docs say: "By definition the score is bounded between 0 and 1"

Both of these are incorrect:
- SMAPE ranges between [0,2]
- R^2 ranges between (-∞,1]
  - This is true when generalized beyond linear models, _as is the case for torchmetrics._
  - But tbh it might be helpful to add an **optional** flag that can clip the range to [-1,1], for the sake of tensorboard readability? _I'll leave this decision to you._

P.S. 
Here is an example tensorboard plot that is hard to read due to exploding negative R^2:
<img width="372" alt="Screenshot 2024-09-15 at 2 10 17 PM" src="https://github.com/user-attachments/assets/4755af12-7da0-49a2-9684-ec469278e09f">

**Comment by SkafteNicki** [comment]
PR #2771 fixes the incorrect statements in the docs but the clipping feature is not implemented as it is a very specific feature that depends on the usecase (sometimes it may be beneficial to know if the r2 score is highly negative indicating a very bad model)
