### ISSUE TITLE
Changing _modules dict type in Pytorch 2.5 leads to failing collections test

### ISSUE THREAD

**Issue by bfolie** [Lightning-AI/torchmetrics#2789]
## 🐛 Bug

As of PyTorch 2.5, the `Module._modules` attribute has [changed](https://github.com/pytorch/pytorch/commit/6120aa3718737dac685eb779ccc4539d4ba059d2#diff-4be56271f7bfe650e3521c81fd363da58f109cd23ee80d243156d2d6ccda6263L497) from an `OrderedDict` to a `dict`. This was done to improve the performance of certain TorchDynamo guard mechanisms and is not expected to affect other behavior because, as of Python 3.7, dictionaries are [ordered by default](https://docs.python.org/3/whatsnew/3.7.html).

This means that [MetricCollection.keys](https://github.com/Lightning-AI/torchmetrics/blob/10339a27424c8fb38ad459082a8a8405dac8e119/src/torchmetrics/collections.py#L513) returns type `dict_keys` when `keep_base=True` but returns `odict_keys` when `keep_base=False` because it uses [_to_renamed_ordered_dict](https://github.com/Lightning-AI/torchmetrics/blob/10339a27424c8fb38ad459082a8a8405dac8e119/src/torchmetrics/collections.py#L502) to construct a new `OrderedDict` (MetricCollection.items has the same issue).

As a result, [test_metric_collection_prefix_postfix_args](https://github.com/Lightning-AI/torchmetrics/blob/6a23b38bae23930de18798cde96a927ad0029b33/tests/unittests/bases/test_collections.py#L164) fails at line 200 because it calls `.keys()` with `keep_base` equal to both True and False and asserts that the resulting types are the same, which they are not.

### Proposed Fix

Change `_to_renamed_ordered_dict` so that it produces either a `dict` or an `OrderedDict`, depending on the type of the existing `_modules` dictionary. This will work for both older and newer version of PyTorch.

Current:
```py
def _to_renamed_ordered_dict(self) -> OrderedDict:
    od = OrderedDict()
    for k, v in self._modules.items():
        od[self._set_name(k)] = v
    return od
```

Proposed:
```py
def _to_renamed_dict(self) -> dict:
    if isinstance(self._modules, OrderedDict):
        d = OrderedDict()
    else:
        d = dict()
    for k, v in self._modules.items():
        d[self._set_name(k)] = v
    return d
```

### To Reproduce

Run the unit tests with PyTorch 2.5

**Comment by bfolie** [comment]
I am happy to implement the proposed fix

**Comment by SkafteNicki** [comment]
Hi @bfolie, we be happy to receive a fix from you :)

**Comment by Borda** [comment]
@bfolie could you pls send a PR with this fix asap so we can rollout the compatibility check for PT 2.5

**Comment by bfolie** [comment]
Hi @Borda , @SkafteNicki . I made the proposed change and confirmed locally that the test passes using both PT 2.4.1 and 2.5.0. But when I try to push my branch I get an error
```
remote: Permission to Lightning-AI/torchmetrics.git denied to bfolie.
fatal: unable to access 'https://github.com/Lightning-AI/torchmetrics/': The requested URL returned error: 403
```

Are there restrictions on who can create new branches?

**Comment by SkafteNicki** [comment]
> Hi @Borda , @SkafteNicki . I made the proposed change and confirmed locally that the test passes using both PT 2.4.1 and 2.5.0. But when I try to push my branch I get an error
> ```
> remote: Permission to Lightning-AI/torchmetrics.git denied to bfolie.
> fatal: unable to access 'https://github.com/Lightning-AI/torchmetrics/': The requested URL returned error: 403
> ```
> 
> Are there restrictions on who can create new branches? 

Yes only members of lightning organizations can push directly. You need to create a fork of the repository, and then push your changes to that. Then you should be able to create a PR from your fork against the main repo
