### ISSUE TITLE
Large computation speed regression in version 1.6.0 on MPS device

### ISSUE THREAD

**Issue by laclouis5** [Lightning-AI/torchmetrics#2868]
## 🐛 Bug

I upgraded to Torchmetrics 1.6.0 and observed a 10x speed drop in the computation of segmentation metrics on MPS device using an Apple MacBook Pro M1 Pro.

### To Reproduce

This code reproduces the issue (run with `uv` or install manually the dependencies):

```python
# /// script
# dependencies = [
#   "torch>=2.4",
#   "torchmetrics>=1.6",
#   "tqdm",
# ]
# ///

import torch
import torchmetrics
from tqdm import tqdm

device = "mps"

metric_params = {
    "task": "multiclass",
    "average": "none",
    "num_classes": 4,
}

metrics = torchmetrics.MetricCollection(
    metrics={
        "F1Score": torchmetrics.F1Score(**metric_params),
        "IoU": torchmetrics.JaccardIndex(**metric_params),
        "Recall": torchmetrics.Recall(**metric_params),
        "Precision": torchmetrics.Precision(**metric_params),
    },
).to(device=device)

input = torch.randn(2, 4, 1024, 1024).to(device=device)
labels = torch.randint(2, 4, (2, 1024, 1024)).to(device=device)

for _ in tqdm(range(100)):
    _ = metrics.update(input, labels)
```

This results in around 1.5 it/s while changing the torchmetrics version to `torchmetrics<1.6` recovers the original speed of 10 it/s.

### Expected behavior

No speed regression expected or documentation on the new behavior.

### Environment

- TorchMetrics version (if build from source, add commit SHA): 1.6.0
- Python & PyTorch Version (e.g., 1.0): 3.11 & 2.5.1
- Any other relevant information such as OS (e.g., Linux): macOS 15.1.1

**Comment by Isalia20** [comment]
I think I have an idea how to fix this. @justusschock  @Borda  may I submit a PR for you to review?

**Comment by Borda** [comment]
> I think I have an idea how to fix this. @justusschock @Borda may I submit a PR for you to review?

Sure, that would be very welcome...

**Comment by Isalia20** [comment]
Yes sure, I'll submit it in an hour

**Comment by Isalia20** [comment]
Submitted
