### ISSUE TITLE
Add IoU/GIoU for boxes

### ISSUE THREAD

**Issue by twsl** [Lightning-AI/torchmetrics#659]
### Motivation

IoU/GIoU are ametrics essential for the detection domain.

### Pitch

Add metrics, for fast implementation these could be based on torchvisions functions.

**Comment by Borda** [comment]
I think we can use this code, right?
https://github.com/PyTorchLightning/lightning-bolts/blob/0.5.0/pl_bolts/metrics/object_detection.py

**Comment by twsl** [comment]
There is an even easier solution if we use torchvision. I can create a draft tomorrow

**Comment by Borda** [comment]
> There is an even easier solution if we use torchvision. I can create a draft tomorrow

I would try to keep own implementations if possible :rabbit:

**Comment by jscottcronin** [comment]
@Borda - I can take this issue :)
