### ISSUE TITLE
Unable to cross-reference a metric in the sphinx doc.

### ISSUE THREAD

**Issue by freud14** [Lightning-AI/torchmetrics#865]
## 🐛 Bug

When trying to cross-reference a metric in another sphinx doc using for instance `` :class:`torchmetrics.AUROC` ``, the link is not created. Looking at the result of `python -m sphinx.ext.intersphinx https://torchmetrics.readthedocs.io/en/latest/objects.inv | grep AUROC`, you can see that there are no entry for `torchmetrics.AUROC`.

### To Reproduce

1. Add torchmetrics entry into conf.py:
    ```python
    intersphinx_mapping = {
        'torchmetrics': ('https://torchmetrics.readthedocs.io/en/latest/', None),
    }
    ```
2. Create link `` :class:`torchmetrics.AUROC` ``.

### Expected behavior

There should be a link created leading to the documentation of the module.

### Additional context

In the [documentation source code](https://github.com/PyTorchLightning/metrics/blob/master/docs/source/references/modules.rst), there are `:noindex:` on each class. I suggest changing all of them to [:noindexentry:](https://github.com/sphinx-doc/sphinx/pull/7906) as I believe it was the original intention.

**Comment by Borda** [comment]
> I suggest changing all of them to [:noindexentry:](https://github.com/sphinx-doc/sphinx/pull/7906) as I believe it was the original intention.

didn't know it, mind sending a PR? :)

**Comment by freud14** [comment]
> > I suggest changing all of them to [:noindexentry:](https://github.com/sphinx-doc/sphinx/pull/7906) as I believe it was the original intention.
> 
> didn't know it, mind sending a PR? :)

Hi, unfortunately, it seems that this works only with "modules" and not autodoc. I just made an issue in Sphinx: https://github.com/sphinx-doc/sphinx/issues/10222 .
