### ISSUE TITLE
Metrics for Levenshtein edit-distance between two strings

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/torchmetrics#937]
## 🚀 Feature

I want to calculate `edit_distance` between two strings. I would prefer an API similar to [NLTK.metrics](https://www.nltk.org/api/nltk.metrics.distance.html#module-nltk.metrics.distance)

### Pitch

```python
from torchmetrics.functional import edit_distance

text1 = "rain"
text2 = "shine"

print(edit_distance(text1, text2)

# >> 3
```

### Alternatives
```python
from nltk.metrics.distance import edit_distance

text1 = "rain"
text2 = "shine"

print(edit_distance(text1, text2)

```

### Additional context

cc: @Borda @stancld

**Comment by avinashsai** [comment]
@SkafteNicki @Borda Can I take this up?

**Comment by Borda** [comment]
@avinashsai sure, you are more than welcome!

**Comment by stancld** [comment]
@avinashsai I think this implementation can be definitely used for creating Public API metric :] However, I'm not really sure if this implementation matches the one from NLTK metrics as I suspect there are multiple edit distance implementations.
