### ISSUE TITLE
Tests: Prepare reference scores once for all env. configs

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/torchmetrics#949]
## 🚀 Feature

If we use the reference metric only for generating static results, these results will be loaded and used in all testing environments?

The proposed flow is semi-online; still, the references are generated during CI test time but only once and shared to remaining tests... so consider using some JSON or YAML universal format.

_TIP1: The references can be shared among jobs as artifact:rabbit:_ 

_TIP2: To speed up we can use some caching with limited time as we do for pip/package caching_

For example, the case with all Condas:
1. create all testing references with frozen env that is supported by all reference metrics
2. run full matric of all configurations PT v{1.4, ...1.12}

### Motivation

this may help to unblock various configurations and also:
- guarantee that the results are identical regardless of env. and if needed, they can be inspected...
- testing could be faster as references are not computed for each config...
- we have not locked with testing for env that the reference packages support...

### Pitch

Make tests more predictable and scalable.

### Alternatives

Still generating on-the-fly results, BUT let's discuss this option a bit... :)

### Additional context

part of #678
pls comment @PyTorchLightning/core-metrics

**Comment by justusschock** [comment]
I support this option in general, I just request that this is implemented with proper caching to ensure that the reference creation is fast most of the time and frequent cache-invalidation that we are always up to date.

@Borda knows all this already since we discussed offline, but mentioning it here for completeness :)
